import { X } from 'lucide-react';
import { RegisteredUserSearch } from './registered-user-search';

export interface CreatureStatField { key:string;label:string;type:'TEXT'|'NUMBER'|'BOOLEAN';required:boolean }
export interface CreatureStatTemplate { id:string;name:string;description:string;fields:CreatureStatField[] }

export interface SpecializedFormState {
  entityType:string;
  playerUserId:string; playerDisplayName:string; characterPronouns:string; characterConcept:string; characterStatus:string; characterNotes:string;
  npcRole:string; npcOccupation:string; npcMotivation:string; npcPublicNotes:string; npcGmNotes:string;
  creatureClassification:string; creatureHabitat:string; creatureBehavior:string; creatureDangerNotes:string; creatureTemplateId:string;
  creatureStatValues:Record<string,string|number|boolean>;
  factionPurpose:string; factionScope:string; factionStatus:string; factionPublicDescription:string; factionGmNotes:string;
  itemType:string; itemRarity:string; itemPublicDescription:string; itemGmNotes:string;
}

export function SpecializedEntityFields({form,templates,update,updateStat}:{
  form:SpecializedFormState;templates:CreatureStatTemplate[];
  update:(key:keyof SpecializedFormState,value:SpecializedFormState[keyof SpecializedFormState])=>void;
  updateStat:(key:string,value:string|number|boolean)=>void;
}) {
  if(form.entityType==='CHARACTER')return <fieldset className="span-2 adventure-fields"><legend>Personagem</legend><label>Pronomes<input maxLength={80} value={form.characterPronouns} onChange={(event)=>update('characterPronouns',event.target.value)}/></label><label>Status<input maxLength={80} value={form.characterStatus} onChange={(event)=>update('characterStatus',event.target.value)}/></label><label className="span-2">Conceito<textarea rows={3} maxLength={1000} value={form.characterConcept} onChange={(event)=>update('characterConcept',event.target.value)}/></label><div className="span-2 specialized-user"><strong>Conta do jogador</strong>{form.playerUserId?<div className="selected-user"><span>{form.playerDisplayName}</span><button type="button" className="ghost-button" onClick={()=>{update('playerUserId','');update('playerDisplayName','');}}><X size={16}/>Remover</button></div>:<RegisteredUserSearch allowGameMaster={false} addLabel="Vincular personagem" onAdd={async(user)=>{update('playerUserId',user.id);update('playerDisplayName',user.displayName);}}/>}</div><label className="span-2">Notas<textarea rows={4} maxLength={10000} value={form.characterNotes} onChange={(event)=>update('characterNotes',event.target.value)}/></label></fieldset>;
  if(form.entityType==='NPC')return <fieldset className="span-2 adventure-fields"><legend>NPC</legend><label>Papel<input maxLength={160} value={form.npcRole} onChange={(event)=>update('npcRole',event.target.value)}/></label><label>Ocupação<input maxLength={160} value={form.npcOccupation} onChange={(event)=>update('npcOccupation',event.target.value)}/></label><label className="span-2">Motivação<textarea rows={3} maxLength={2000} value={form.npcMotivation} onChange={(event)=>update('npcMotivation',event.target.value)}/></label><label className="span-2">Notas públicas<textarea rows={4} maxLength={10000} value={form.npcPublicNotes} onChange={(event)=>update('npcPublicNotes',event.target.value)}/></label><label className="span-2 gm-field">Notas do narrador <small>Nunca são enviadas pela API para jogadores.</small><textarea rows={4} maxLength={10000} value={form.npcGmNotes} onChange={(event)=>update('npcGmNotes',event.target.value)}/></label></fieldset>;
  if(form.entityType==='CREATURE'){const template=templates.find((item)=>item.id===form.creatureTemplateId);return <fieldset className="span-2 adventure-fields"><legend>Bestiário</legend><label>Classificação<input maxLength={160} value={form.creatureClassification} onChange={(event)=>update('creatureClassification',event.target.value)}/></label><label>Habitat<input maxLength={1000} value={form.creatureHabitat} onChange={(event)=>update('creatureHabitat',event.target.value)}/></label><label className="span-2">Comportamento<textarea rows={4} maxLength={5000} value={form.creatureBehavior} onChange={(event)=>update('creatureBehavior',event.target.value)}/></label><label className="span-2">Notas de perigo<textarea rows={3} maxLength={5000} value={form.creatureDangerNotes} onChange={(event)=>update('creatureDangerNotes',event.target.value)}/></label><label className="span-2">Modelo de estatísticas<select value={form.creatureTemplateId} onChange={(event)=>{update('creatureTemplateId',event.target.value);update('creatureStatValues',{});}}><option value="">Sem ficha estruturada</option>{templates.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><small>Os campos são definidos no Bestiário do World, sem atributos fixos.</small></label>{template?.fields.map((field)=><label key={field.key}>{field.label}{field.type==='BOOLEAN'?<select value={String(form.creatureStatValues[field.key]??'')} required={field.required} onChange={(event)=>updateStat(field.key,event.target.value==='true')}><option value="">Não definido</option><option value="true">Sim</option><option value="false">Não</option></select>:<input type={field.type==='NUMBER'?'number':'text'} required={field.required} value={String(form.creatureStatValues[field.key]??'')} onChange={(event)=>updateStat(field.key,field.type==='NUMBER'&&event.target.value!==''?Number(event.target.value):event.target.value)}/>}</label>)}</fieldset>}
  if(form.entityType==='FACTION')return <fieldset className="span-2 adventure-fields"><legend>Facção</legend><label>Escopo<input maxLength={160} value={form.factionScope} onChange={(event)=>update('factionScope',event.target.value)}/></label><label>Status<input maxLength={80} value={form.factionStatus} onChange={(event)=>update('factionStatus',event.target.value)}/></label><label className="span-2">Propósito<textarea rows={3} maxLength={2000} value={form.factionPurpose} onChange={(event)=>update('factionPurpose',event.target.value)}/></label><label className="span-2">Descrição pública<textarea rows={4} maxLength={10000} value={form.factionPublicDescription} onChange={(event)=>update('factionPublicDescription',event.target.value)}/></label><label className="span-2 gm-field">Notas do narrador<textarea rows={4} maxLength={10000} value={form.factionGmNotes} onChange={(event)=>update('factionGmNotes',event.target.value)}/></label></fieldset>;
  if(form.entityType==='ITEM')return <fieldset className="span-2 adventure-fields"><legend>Item</legend><label>Tipo de item<input maxLength={160} value={form.itemType} onChange={(event)=>update('itemType',event.target.value)}/></label><label>Raridade<input maxLength={80} value={form.itemRarity} onChange={(event)=>update('itemRarity',event.target.value)}/></label><label className="span-2">Descrição pública<textarea rows={4} maxLength={10000} value={form.itemPublicDescription} onChange={(event)=>update('itemPublicDescription',event.target.value)}/></label><label className="span-2 gm-field">Notas do narrador<textarea rows={4} maxLength={10000} value={form.itemGmNotes} onChange={(event)=>update('itemGmNotes',event.target.value)}/></label></fieldset>;
  return null;
}

export function SpecializedEntityDetails({character,npc,creature,faction,item}:{
  character:{playerDisplayName:string|null;pronouns:string;concept:string;status:string;notes:string}|null;
  npc:{role:string;occupation:string;motivation:string;publicNotes:string;gmNotes?:string}|null;
  creature:{classification:string;habitat:string;behavior:string;dangerNotes:string;statBlock:{templateName:string;fields:CreatureStatField[];values:Record<string,string|number|boolean>}|null}|null;
  faction:{purpose:string;scope:string;status:string;publicDescription:string;gmNotes?:string}|null;
  item:{itemType:string;rarity:string;publicDescription:string;gmNotes?:string}|null;
}) {
  if(character)return <><h3>Personagem</h3><dl><Detail label="Jogador" value={character.playerDisplayName}/><Detail label="Pronomes" value={character.pronouns}/><Detail label="Conceito" value={character.concept}/><Detail label="Status" value={character.status}/></dl>{character.notes&&<TextDetail label="Notas" value={character.notes}/>}</>;
  if(npc)return <><h3>NPC</h3><dl><Detail label="Papel" value={npc.role}/><Detail label="Ocupação" value={npc.occupation}/><Detail label="Motivação" value={npc.motivation}/></dl><TextDetail label="Notas públicas" value={npc.publicNotes}/>{npc.gmNotes!==undefined&&<TextDetail label="Notas do narrador" value={npc.gmNotes} secret/>}</>;
  if(creature)return <><h3>Bestiário</h3><dl><Detail label="Classificação" value={creature.classification}/><Detail label="Habitat" value={creature.habitat}/></dl><TextDetail label="Comportamento" value={creature.behavior}/><TextDetail label="Notas de perigo" value={creature.dangerNotes}/>{creature.statBlock&&<div className="stat-block"><h4>{creature.statBlock.templateName}</h4><dl>{creature.statBlock.fields.map((field)=><Detail key={field.key} label={field.label} value={formatStatValue(creature.statBlock?.values[field.key])}/>)}</dl></div>}</>;
  if(faction)return <><h3>Facção</h3><dl><Detail label="Escopo" value={faction.scope}/><Detail label="Status" value={faction.status}/><Detail label="Propósito" value={faction.purpose}/></dl><TextDetail label="Descrição pública" value={faction.publicDescription}/>{faction.gmNotes!==undefined&&<TextDetail label="Notas do narrador" value={faction.gmNotes} secret/>}</>;
  if(item)return <><h3>Item</h3><dl><Detail label="Tipo" value={item.itemType}/><Detail label="Raridade" value={item.rarity}/></dl><TextDetail label="Descrição pública" value={item.publicDescription}/>{item.gmNotes!==undefined&&<TextDetail label="Notas do narrador" value={item.gmNotes} secret/>}</>;
  return null;
}

function Detail({label,value}:{label:string;value:string|null|undefined}){return <div><dt>{label}</dt><dd>{value||'Não informado'}</dd></div>}
function TextDetail({label,value,secret=false}:{label:string;value:string;secret?:boolean}){if(!value)return null;return <div className={secret?'gm-detail':''}><h4>{label}</h4><p className="pre-wrap">{value}</p></div>}
function formatStatValue(value:string|number|boolean|undefined){if(value===true)return'Sim';if(value===false)return'Não';return value===undefined||value===''?'Não informado':String(value)}
