-- Expands the reference taxonomy without changing identifiers already in use.
INSERT OR IGNORE INTO categories (id, name, sort_order) VALUES
  ('acao-aventura', 'Ação e Aventura', 10),
  ('alternativo', 'Alternativo', 20),
  ('animais', 'Animais', 30),
  ('anime-quadrinhos', 'Anime e Quadrinhos', 40),
  ('comedia-satira', 'Comédia e Sátira', 50),
  ('crime-misterio', 'Crime e Mistério', 60),
  ('cultura-mitologia', 'Cultura, Mitologia e Folclore', 70),
  ('estranho-surreal', 'Estranho e Surreal', 80),
  ('fantasia', 'Fantasia', 90),
  ('ficcao-cientifica', 'Ficção Científica', 100),
  ('guerra-militar', 'Guerra e Militar', 110),
  ('historico', 'Histórico', 120),
  ('horror', 'Horror', 130),
  ('infantil', 'Infantil', 140),
  ('moderno', 'Moderno', 150),
  ('pos-apocaliptico', 'Pós-Apocalíptico', 160),
  ('social-politico', 'Social e Político', 170),
  ('universal', 'Universal', 180);

UPDATE categories SET sort_order=20 WHERE id='alternativo';
UPDATE categories SET sort_order=90 WHERE id='fantasia';
UPDATE categories SET sort_order=100 WHERE id='ficcao-cientifica';
UPDATE categories SET sort_order=130 WHERE id='horror';
UPDATE categories SET sort_order=150 WHERE id='moderno';
UPDATE categories SET sort_order=160 WHERE id='pos-apocaliptico';
UPDATE categories SET sort_order=180 WHERE id='universal';

INSERT OR IGNORE INTO subgenres (id, category_id, name) VALUES
  ('aventura-geral', 'acao-aventura', 'Aventura'),
  ('gangster-mafia', 'acao-aventura', 'Gangsters e Máfia'),
  ('nautico', 'acao-aventura', 'Náutico'),
  ('piratas-capa-espada', 'acao-aventura', 'Piratas e Capa e Espada'),
  ('pulp', 'acao-aventura', 'Pulp'),
  ('esportes', 'acao-aventura', 'Esportes'),
  ('super-herois-acao', 'acao-aventura', 'Super-Heróis'),
  ('steampunk', 'alternativo', 'Steampunk'),
  ('dieselpunk', 'alternativo', 'Dieselpunk'),
  ('kaiju', 'alternativo', 'Kaiju'),
  ('garota-magica', 'alternativo', 'Garota Mágica'),
  ('cacadores-monstros', 'alternativo', 'Caçadores de Monstros'),
  ('multiverso', 'alternativo', 'Multiverso'),
  ('wuxia', 'alternativo', 'Wuxia'),
  ('artes-marciais', 'alternativo', 'Artes Marciais'),
  ('antropomorficos', 'animais', 'Animais Antropomórficos'),
  ('animais-protagonistas', 'animais', 'Animais Protagonistas'),
  ('anime-manga', 'anime-quadrinhos', 'Anime e Mangá'),
  ('cartum-quadrinhos-ocidentais', 'anime-quadrinhos', 'Cartum e Quadrinhos Ocidentais'),
  ('jrpg', 'anime-quadrinhos', 'Fantasia de JRPG'),
  ('comedia', 'comedia-satira', 'Comédia'),
  ('satira', 'comedia-satira', 'Sátira'),
  ('humor-negro', 'comedia-satira', 'Humor Negro'),
  ('conspiracao', 'crime-misterio', 'Conspiração'),
  ('criminosos-mafia', 'crime-misterio', 'Crime Organizado'),
  ('detetive-noir', 'crime-misterio', 'Detetive e Noir'),
  ('espionagem', 'crime-misterio', 'Espionagem'),
  ('policial', 'crime-misterio', 'Policial'),
  ('misterio', 'crime-misterio', 'Mistério'),
  ('cultura-africana', 'cultura-mitologia', 'Culturas Africanas'),
  ('cultura-americas', 'cultura-mitologia', 'Culturas das Américas'),
  ('cultura-asiatica', 'cultura-mitologia', 'Culturas Asiáticas'),
  ('cultura-europeia', 'cultura-mitologia', 'Culturas Europeias'),
  ('contos-fadas', 'cultura-mitologia', 'Contos de Fadas'),
  ('folclore', 'cultura-mitologia', 'Folclore'),
  ('mitologia', 'cultura-mitologia', 'Mitologia'),
  ('religiao', 'cultura-mitologia', 'Religião'),
  ('ocultismo', 'cultura-mitologia', 'Ocultismo'),
  ('magia-ritual', 'cultura-mitologia', 'Magia Ritual'),
  ('psionismo', 'cultura-mitologia', 'Psionismo e Mentalismo'),
  ('tarot-simbolismo', 'cultura-mitologia', 'Tarô e Simbolismo'),
  ('surrealismo', 'estranho-surreal', 'Surrealismo'),
  ('new-weird', 'estranho-surreal', 'New Weird'),
  ('ficcao-estranha', 'estranho-surreal', 'Ficção Estranha'),
  ('fantasia-arabica', 'fantasia', 'Fantasia das Mil e Uma Noites'),
  ('fantasia-arturiana', 'fantasia', 'Fantasia Arturiana'),
  ('baixa-fantasia', 'fantasia', 'Baixa Fantasia'),
  ('fantasia-cientifica', 'fantasia', 'Fantasia Científica'),
  ('portal-fantasy', 'fantasia', 'Fantasia de Portal'),
  ('fantasia-contemporanea', 'fantasia', 'Fantasia Contemporânea'),
  ('hard-sci-fi', 'ficcao-cientifica', 'Ficção Científica Hard'),
  ('space-opera', 'ficcao-cientifica', 'Space Opera'),
  ('cyberpunk', 'ficcao-cientifica', 'Cyberpunk'),
  ('mecha', 'ficcao-cientifica', 'Mecha'),
  ('viagem-tempo-dimensoes', 'ficcao-cientifica', 'Viagem no Tempo e Dimensões'),
  ('primeiro-contato', 'ficcao-cientifica', 'Primeiro Contato'),
  ('transumanismo', 'ficcao-cientifica', 'Transumanismo'),
  ('ficcao-cientifica-militar', 'ficcao-cientifica', 'Ficção Científica Militar'),
  ('guerra-geral', 'guerra-militar', 'Guerra'),
  ('militar', 'guerra-militar', 'Militar'),
  ('guerra-naval', 'guerra-militar', 'Guerra Naval'),
  ('guerra-aerea', 'guerra-militar', 'Guerra Aérea'),
  ('historia-alternativa', 'historico', 'História Alternativa'),
  ('oeste-americano', 'historico', 'Oeste Americano'),
  ('antiguidade', 'historico', 'Antiguidade'),
  ('medieval-historico', 'historico', 'Medieval'),
  ('pre-historia', 'historico', 'Pré-História'),
  ('renascimento', 'historico', 'Renascimento'),
  ('era-vitoriana', 'historico', 'Era Vitoriana'),
  ('vikings', 'historico', 'Vikings'),
  ('seculo-xx', 'historico', 'Século XX'),
  ('horror-gotico', 'horror', 'Horror Gótico'),
  ('horror-sobrenatural', 'horror', 'Horror Sobrenatural'),
  ('horror-folclorico', 'horror', 'Horror Folclórico'),
  ('body-horror', 'horror', 'Horror Corporal'),
  ('slasher', 'horror', 'Slasher'),
  ('zumbis-horror', 'horror', 'Zumbis'),
  ('infancia', 'infantil', 'Infância'),
  ('familia', 'infantil', 'Para Toda a Família'),
  ('aventura-infantil', 'infantil', 'Aventura Infantil'),
  ('acao-moderna', 'moderno', 'Ação Contemporânea'),
  ('contemporaneo-urbano', 'moderno', 'Urbano Contemporâneo'),
  ('futuro-proximo', 'moderno', 'Futuro Próximo'),
  ('cultura-pop', 'moderno', 'Cultura Pop'),
  ('tecnothriller', 'moderno', 'Tecnothriller'),
  ('apocalipse-zumbi', 'pos-apocaliptico', 'Apocalipse Zumbi'),
  ('colapso-climatico', 'pos-apocaliptico', 'Colapso Climático'),
  ('deserto-pos-apocaliptico', 'pos-apocaliptico', 'Ermos e Sobrevivência'),
  ('pos-apocalipse-magico', 'pos-apocaliptico', 'Pós-Apocalipse Mágico'),
  ('corporacoes', 'social-politico', 'Corporações'),
  ('drama', 'social-politico', 'Drama'),
  ('politica-governo', 'social-politico', 'Política e Governo'),
  ('relacionamentos-romance', 'social-politico', 'Relacionamentos e Romance'),
  ('slice-of-life', 'social-politico', 'Cotidiano / Slice of Life'),
  ('utopia-distopia', 'social-politico', 'Utopia e Distopia'),
  ('generico-universal', 'universal', 'Genérico / Universal'),
  ('sistema-multigenero', 'universal', 'Sistema Multigênero');

ALTER TABLE play_group_members ADD COLUMN user_id TEXT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE play_group_members ADD COLUMN is_game_master INTEGER NOT NULL DEFAULT 0 CHECK(is_game_master IN (0,1));
CREATE UNIQUE INDEX idx_play_group_members_registered_user ON play_group_members(group_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX idx_play_group_single_game_master ON play_group_members(group_id) WHERE is_game_master=1;
CREATE INDEX idx_play_group_members_user ON play_group_members(user_id);

ALTER TABLE campaign_members ADD COLUMN user_id TEXT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE campaign_members ADD COLUMN is_game_master INTEGER NOT NULL DEFAULT 0 CHECK(is_game_master IN (0,1));
CREATE UNIQUE INDEX idx_campaign_members_registered_user ON campaign_members(campaign_id, user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_campaign_members_user ON campaign_members(user_id);
