import { BookMarked, Download, KeyRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom';
import { ClientApiError, postJson } from '../api/client';
import { useAuth, type User } from '../auth/auth-context';
import { Turnstile } from '../components/turnstile';

function AuthFrame({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <main className="auth-page"><section className="auth-story"><BookMarked size={38}/><h1>Sua estante. Suas mesas.<br/>Suas histórias.</h1><p>Organize leituras, escolha o próximo jogo e acompanhe cada campanha sem perder o fio da aventura.</p></section><section className="auth-panel"><div className="auth-card"><span className="eyebrow">RPG Manager</span><h2>{title}</h2><p>{subtitle}</p>{children}</div></section></main>}
function ErrorText({error}:{error:string}){return error?<p className="form-error" role="alert">{error}</p>:null;}
function authError(reason: unknown): string { if (!(reason instanceof ClientApiError)) return 'Falha inesperada.'; return reason.requestId && reason.status >= 500 ? `${reason.message} Código de suporte: ${reason.requestId}` : reason.message; }
function safeReturnPath(value: string | null): string { return value?.startsWith('/') && !value.startsWith('//') ? value : '/app'; }

export function LoginPage(){const {user,setUser}=useAuth();const navigate=useNavigate();const [searchParams]=useSearchParams();const returnPath=safeReturnPath(searchParams.get('returnTo'));const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [token,setToken]=useState('');if(user)return <Navigate to={returnPath} replace/>;
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{const result=await postJson<{user:User}>('/auth/login',{email:data.get('email'),password:data.get('password'),turnstileToken:token||undefined});setUser(result.user);navigate(returnPath);}catch(reason){setError(authError(reason));}finally{setBusy(false);}};
  return <AuthFrame title="Bem-vindo de volta" subtitle="Entre para continuar sua próxima aventura."><form onSubmit={submit}><label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha<input name="password" type="password" autoComplete="current-password" required/></label><Turnstile onToken={setToken}/><ErrorText error={error}/><button className="primary-button" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form><div className="auth-links"><Link to="/recover-account">Usar código de recuperação</Link><span>Não tem conta? <Link to={`/register?returnTo=${encodeURIComponent(returnPath)}`}>Criar conta</Link></span></div></AuthFrame>}

export function RegisterPage(){const {user,setUser}=useAuth();const [searchParams]=useSearchParams();const returnPath=safeReturnPath(searchParams.get('returnTo'));const [codes,setCodes]=useState<string[]>([]);const [error,setError]=useState('');const [token,setToken]=useState('');const [busy,setBusy]=useState(false);const [turnstileAttempt,setTurnstileAttempt]=useState(0);if(user&&!codes.length)return <Navigate to={returnPath} replace/>;
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);if(data.get('password')!==data.get('confirm')){setError('As senhas não coincidem.');setBusy(false);return;}try{const result=await postJson<{user:User;recoveryCodes:string[]}>('/auth/register',{email:data.get('email'),displayName:data.get('displayName'),password:data.get('password'),turnstileToken:token||undefined});setUser(result.user);setCodes(result.recoveryCodes);}catch(reason){setError(authError(reason));setToken('');setTurnstileAttempt((value)=>value+1);}finally{setBusy(false);}};
  if(codes.length){const download=()=>{const blob=new Blob([`RPG Manager — códigos de recuperação\n\n${codes.join('\n')}\n`],{type:'text/plain'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='rpg-manager-recovery-codes.txt';link.click();URL.revokeObjectURL(link.href);};return <AuthFrame title="Guarde seus códigos" subtitle="Eles serão mostrados somente agora e cada um funciona uma única vez."><div className="recovery-codes">{codes.map(code=><code key={code}>{code}</code>)}</div><button className="secondary-button" onClick={()=>void navigator.clipboard.writeText(codes.join('\n'))}>Copiar códigos</button><button className="secondary-button" onClick={download}><Download size={17}/>Baixar TXT</button><Link className="primary-button link-button" to={returnPath}>Já guardei, continuar</Link></AuthFrame>}
  return <AuthFrame title="Crie sua biblioteca" subtitle="Comece com uma senha longa e guarde os códigos de recuperação."><form onSubmit={submit}><label>Como quer ser chamado?<input name="displayName" autoComplete="name" maxLength={80} required/></label><label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha <small>mínimo de 12 caracteres</small><input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><label>Confirmar senha<input name="confirm" type="password" minLength={12} autoComplete="new-password" required/></label><Turnstile key={turnstileAttempt} onToken={setToken}/><ErrorText error={error}/><button className="primary-button" disabled={busy}>{busy?'Criando conta…':'Criar conta'}</button></form><div className="auth-links">Já tem conta? <Link to={`/login?returnTo=${encodeURIComponent(returnPath)}`}>Entrar</Link></div></AuthFrame>}

export function RecoverPage(){const {setUser}=useAuth();const navigate=useNavigate();const [error,setError]=useState('');const [token,setToken]=useState('');const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);try{const result=await postJson<{user:User}>('/auth/recover',{email:data.get('email'),recoveryCode:data.get('code'),newPassword:data.get('password'),turnstileToken:token||undefined});setUser(result.user);navigate('/app');}catch(reason){setError(authError(reason));}};return <AuthFrame title="Recuperar conta" subtitle="Use um dos códigos guardados no cadastro e defina uma nova senha."><form onSubmit={submit}><label>E-mail<input name="email" type="email" required/></label><label>Código de recuperação<div className="input-icon"><KeyRound size={17}/><input name="code" autoCapitalize="characters" required/></div></label><label>Nova senha<input name="password" type="password" minLength={12} maxLength={128} required/></label><Turnstile onToken={setToken}/><ErrorText error={error}/><button className="primary-button">Recuperar conta</button></form><div className="auth-links"><Link to="/login">Voltar ao login</Link></div></AuthFrame>}
