import { BookCheck, BookOpen, CalendarDays, Dice5, Library, ScrollText, Target } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api/client';

interface DashboardData { metrics:{total:number;read:number;played:number;wants:number;unread:number;scheduled:number;readingCompletion:number};categories:Array<{name:string;count:number}>;reading:Array<{status:string;count:number}>;recommendations:Array<{id:string;title:string;score:number;priority:string;readingStatus:string;playGroupNotes:string;readiness:string;nextAction:string}>;readingBacklog:Array<{id:string;title:string;readingStatus:string}>;activeTables:Array<{id:string;title:string;tableStatus:string;playGroupNotes:string}>;campaigns:Array<{id:string;name:string;rpgTitle:string;status:string;nextSessionDate:string|null;sessionsCompleted:number;progress:number|null;stage:string;nextAction:string;frequency:string|null}> }
const metricIcons=[Library,BookCheck,Dice5,Target,BookOpen,CalendarDays,ScrollText];
export function DashboardPage(){const [data,setData]=useState<DashboardData>();useEffect(()=>{void api<DashboardData>('/dashboard').then(setData);},[]);if(!data)return <Loading/>;const metricEntries=[['Total de RPGs',data.metrics.total],['Já lidos',data.metrics.read],['Já jogados',data.metrics.played],['Quero jogar',data.metrics.wants],['Ainda não lidos',data.metrics.unread],['Mesas agendadas',data.metrics.scheduled],['Leitura concluída',`${data.metrics.readingCompletion}%`]];
  return <div className="page"><PageHeader eyebrow="Visão geral" title="Painel do aventureiro" description="Sua coleção e o caminho mais curto até a próxima mesa." action={<Link className="primary-button link-button" to="/app/library/new">Adicionar RPG</Link>}/><section className="metric-grid">{metricEntries.map(([label,value],index)=>{const Icon=metricIcons[index];return <article className="metric-card" key={label}><Icon/><span>{label}</span><strong>{value}</strong></article>})}</section>
    {data.metrics.total===0?<Empty title="Sua estante ainda está vazia" text="Cadastre o primeiro RPG ou importe o CSV da sua planilha." action="Adicionar primeiro RPG" to="/app/library/new"/>:<>
    <section className="dashboard-grid"><article className="panel"><h2>O que jogar agora?</h2><p className="section-note">Ranking calculado no servidor a partir de interesse, leitura e prontidão.</p><div className="table-wrap"><table><thead><tr><th>Jogo</th><th>Pontos</th><th>Prioridade</th><th>Prontidão</th><th>Próxima ação</th></tr></thead><tbody>{data.recommendations.map(item=><tr key={item.id}><td><Link to={`/app/library/${item.id}`}>{item.title}</Link></td><td><strong>{item.score}</strong></td><td><Badge>{item.priority}</Badge></td><td>{item.readiness}</td><td>{item.nextAction}</td></tr>)}</tbody></table></div></article>
    <article className="panel chart-panel"><h2>RPGs por categoria</h2>{data.categories.map(item=><div className="bar-row" key={item.name}><span>{item.name}</span><div><i style={{width:`${Math.max(5,item.count/Math.max(...data.categories.map(x=>x.count))*100)}%`}}/></div><strong>{item.count}</strong></div>)}</article></section>
    <section className="dashboard-grid"><article className="panel"><h2>Backlog de leitura</h2>{data.readingBacklog.length?<ul className="clean-list">{data.readingBacklog.map(item=><li key={item.id}><Link to={`/app/library/${item.id}`}>{item.title}</Link><Badge>{item.readingStatus}</Badge></li>)}</ul>:<p>Todas as leituras estão concluídas.</p>}</article><article className="panel"><h2>Mesas em preparação / andamento</h2>{data.activeTables.length?<ul className="clean-list">{data.activeTables.map(item=><li key={item.id}><Link to={`/app/library/${item.id}`}>{item.title}</Link><Badge>{item.tableStatus}</Badge></li>)}</ul>:<p>Nenhuma mesa ativa agora.</p>}</article></section>
    <section className="panel"><div className="section-heading"><div><h2>Planejador de campanhas</h2><p className="section-note">Etapa e próxima ação derivadas da situação real da campanha.</p></div><Link to="/app/campaigns">Ver todas</Link></div>{data.campaigns.length?<div className="table-wrap"><table><thead><tr><th>RPG</th><th>Campanha</th><th>Status</th><th>Próxima sessão</th><th>Sessões</th><th>Progresso</th><th>Etapa</th><th>Próxima ação</th></tr></thead><tbody>{data.campaigns.map(item=><tr key={item.id}><td>{item.rpgTitle}</td><td><Link to={`/app/campaigns/${item.id}`}>{item.name}</Link></td><td><Badge>{item.status}</Badge></td><td>{formatDate(item.nextSessionDate)}</td><td>{item.sessionsCompleted}</td><td>{item.progress===null?'Sem meta':`${item.progress}%`}</td><td>{item.stage}</td><td>{item.nextAction}</td></tr>)}</tbody></table></div>:<Empty title="Nenhuma campanha" text="Transforme um RPG da estante na próxima história do grupo." action="Criar campanha" to="/app/campaigns/new"/>}</section></>}</div>}
export function Loading(){return <div className="loading" role="status"><span/>Carregando grimório…</div>}
export function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</header>}
export function Badge({children}:{children:React.ReactNode}){return <span className="badge">{String(children).replaceAll('_',' ')}</span>}
export function Empty({title,text,action,to}:{title:string;text:string;action:string;to:string}){return <div className="empty-state"><Dice5/><h3>{title}</h3><p>{text}</p><Link className="secondary-button link-button" to={to}>{action}</Link></div>}
export function formatDate(value:string|null|undefined){return value?new Intl.DateTimeFormat('pt-BR').format(new Date(`${value.slice(0,10)}T12:00:00`)):'—'}

