import { Archive, Plus, RotateCcw, Trash2, UsersRound } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api, deleteApi, patchJson, postJson } from '../api/client';
import { RegisteredUserSearch, type DirectoryUser } from '../components/registered-user-search';
import type { Rpg } from './library-pages';
import { Empty, Loading, PageHeader } from './dashboard-page';
import { displayLabel } from '../labels';

interface World {
  id:string; name:string; slug:string; description:string; defaultRpgId:string|null; defaultRpgTitle:string|null;
  visibility:'PRIVATE'|'GROUP'; status:'ACTIVE'|'ARCHIVED'; archivedAt:string|null; isOwner:boolean;
}
interface WorldMember { userId:string; displayName:string; role:'OWNER'|'VIEWER' }
interface RecentEntity { id:string; entityType:string; name:string; summary:string; visibility:string; archivedAt:string|null }

export function WorldsPage(){
  const [items,setItems]=useState<World[]>();const [archive,setArchive]=useState('active');const [search,setSearch]=useState('');
  useEffect(()=>{const params=new URLSearchParams({archive,sort:'recent'});if(search)params.set('search',search);void api<{items:World[]}>(`/worlds?${params}`).then((result)=>setItems(result.items));},[archive,search]);
  return <div className="page"><PageHeader eyebrow="Worlds" title="Seus mundos" description="Organize cenários e reúna todo o conteúdo que existe em cada mundo." action={<Link className="primary-button link-button" to="/app/worlds/new"><Plus size={18}/>Novo World</Link>}/><div className="filters world-filters"><div className="search-box"><input aria-label="Buscar Worlds" value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Buscar por nome"/></div><select aria-label="Filtrar Worlds" value={archive} onChange={(event)=>setArchive(event.target.value)}><option value="active">Ativos</option><option value="archived">Arquivados</option><option value="all">Todos</option></select></div>{!items?<Loading/>:items.length===0?<Empty title="Nenhum World encontrado" text="Crie um mundo para organizar locais, personagens e histórias." action="Criar World" to="/app/worlds/new"/>:<div className="world-grid">{items.map((world)=><Link className="world-card" to={`/app/worlds/${world.id}`} key={world.id}><span className="eyebrow">{world.defaultRpgTitle||'Sistema livre'}</span><h2>{world.name}</h2><p>{world.description||'Este mundo ainda não possui uma descrição.'}</p><div className="entity-meta"><span>{displayLabel(world.visibility)}</span><span>{displayLabel(world.status)}</span></div></Link>)}</div>}</div>;
}

export function WorldFormPage(){
  const {id}=useParams();const navigate=useNavigate();const [rpgs,setRpgs]=useState<Rpg[]>([]);const [form,setForm]=useState({name:'',description:'',defaultRpgId:'',visibility:'PRIVATE'});const [error,setError]=useState('');
  useEffect(()=>{void api<{items:Rpg[]}>('/rpgs?pageSize=100&sort=title').then((result)=>setRpgs(result.items));if(id)void api<{item:World}>(`/worlds/${id}`).then(({item})=>setForm({name:item.name,description:item.description,defaultRpgId:item.defaultRpgId??'',visibility:item.visibility}));},[id]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');try{const payload={...form,defaultRpgId:form.defaultRpgId||null};if(id){await patchJson(`/worlds/${id}`,payload);navigate(`/app/worlds/${id}`);}else{const result=await postJson<{item:World}>('/worlds',payload);navigate(`/app/worlds/${result.item.id}`);}}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível salvar o World.');}};
  return <div className="page narrow"><PageHeader eyebrow={id?'Editar World':'Novo World'} title="Construa um lugar para suas histórias" description="O World agrupa entidades do Vault sem prender seu conteúdo a uma única campanha."/><form className="panel form-grid" onSubmit={submit}><label className="span-2">Nome<input required maxLength={160} value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})}/></label><label>RPG padrão<select value={form.defaultRpgId} onChange={(event)=>setForm({...form,defaultRpgId:event.target.value})}><option value="">Nenhum</option>{rpgs.map((rpg)=><option key={rpg.id} value={rpg.id}>{rpg.title}</option>)}</select></label><label>Visibilidade<select value={form.visibility} onChange={(event)=>setForm({...form,visibility:event.target.value})}><option value="PRIVATE">Privado</option><option value="GROUP">Membros convidados</option></select></label><label className="span-2">Descrição<textarea rows={7} maxLength={10000} value={form.description} onChange={(event)=>setForm({...form,description:event.target.value})}/></label>{error&&<p className="form-error span-2">{error}</p>}<div className="form-actions span-2"><button type="button" className="ghost-button" onClick={()=>navigate(-1)}>Cancelar</button><button className="primary-button">Salvar World</button></div></form></div>;
}

export function WorldDetailPage(){
  const {id}=useParams();const navigate=useNavigate();const [data,setData]=useState<{item:World;counts:Array<{entityType:string;count:number}>;recentEntities:RecentEntity[];members:WorldMember[]}>();const [error,setError]=useState('');
  const load=()=>api<typeof data & {}>(`/worlds/${id}`).then((result)=>setData(result));
  useEffect(()=>{void api<{item:World;counts:Array<{entityType:string;count:number}>;recentEntities:RecentEntity[];members:WorldMember[]}>(`/worlds/${id}`).then(setData);},[id]);
  if(!data)return <Loading/>;const world=data.item;
  const addMember=async(user:DirectoryUser)=>{setError('');try{await postJson(`/worlds/${id}/members`,{userId:user.id});await load();}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível adicionar a conta.');}};
  const archive=async()=>{await postJson(`/worlds/${id}/${world.archivedAt?'restore':'archive'}`,{});await load();};
  return <div className="page"><PageHeader eyebrow={world.defaultRpgTitle||'World'} title={world.name} description={world.description||'Este mundo ainda não possui uma descrição.'} action={world.isOwner?<div className="button-row"><Link className="secondary-button link-button" to={`/app/worlds/${id}/edit`}>Editar</Link><Link className="primary-button link-button" to={`/app/vault/new?worldId=${id}`}><Plus size={17}/>Adicionar entidade</Link></div>:undefined}/><section className="world-summary">{data.counts.length?data.counts.map((count)=><article key={count.entityType}><span>{displayLabel(count.entityType)}</span><strong>{count.count}</strong></article>):<article><span>Conteúdo</span><strong>0</strong></article>}</section><section className="panel"><div className="section-heading"><div><h2>Conteúdo recente</h2><p className="section-note">Entidades que você pode visualizar neste World.</p></div><Link to={`/app/vault?worldId=${id}`}>Abrir no Vault</Link></div>{data.recentEntities.length?<div className="entity-list">{data.recentEntities.map((entity)=><Link key={entity.id} to={`/app/vault/${entity.id}`}><span className="entity-type">{displayLabel(entity.entityType)}</span><div><strong>{entity.name}</strong><p>{entity.summary||'Sem resumo.'}</p></div></Link>)}</div>:<Empty title="Este mundo ainda não possui conteúdo" text="Crie a primeira entidade para começar a construir este cenário." action="Adicionar primeira entidade" to={`/app/vault/new?worldId=${id}`}/>}</section>{world.isOwner&&<section className="panel world-members-panel"><h2><UsersRound size={20}/>Pessoas com acesso</h2><p className="section-note">Membros convidados visualizam o World quando a visibilidade está definida como grupo.</p><RegisteredUserSearch allowGameMaster={false} addLabel="Adicionar ao World" onAdd={(user)=>addMember(user)}/>{error&&<p className="form-error">{error}</p>}<ul className="clean-list">{data.members.map((member)=><li key={member.userId}><span><strong>{member.displayName}</strong><small>{displayLabel(member.role)}</small></span>{member.role==='VIEWER'&&<button className="ghost-button" onClick={async()=>{await deleteApi(`/worlds/${id}/members/${member.userId}`);await load();}}>Remover</button>}</li>)}</ul></section>}{world.isOwner&&<div className="button-row destructive-actions"><button className="secondary-button" onClick={()=>void archive()}>{world.archivedAt?<RotateCcw size={17}/>:<Archive size={17}/>} {world.archivedAt?'Restaurar World':'Arquivar World'}</button><button className="danger-button" onClick={async()=>{if(confirm(`Excluir o World “${world.name}”?`)){try{await deleteApi(`/worlds/${id}`);navigate('/app/worlds');}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível excluir.');}}}}><Trash2 size={17}/>Excluir World</button></div>}</div>;
}
