import { Hono, type Context } from 'hono';
import { canArchiveEntity, canDeleteEntity, canEditEntity, canRestoreEntity } from '../../domain/content/permissions';
import { validateAdventureDetails, validateLocationParent } from '../../domain/content/validation';
import { ENTITY_TYPES, ENTITY_VISIBILITIES, type VaultEntityType } from '../../domain/content/types';
import { vaultEntityInputSchema, type VaultEntityInput } from '../../shared/validation/schemas';
import { ApiError, nowIso, readJson } from '../http';
import { authorizedEntity, entityAccessContext, entityAuthorizationColumns, entityAuthorizationPredicate, entityAuthorizationValues, ownedEntity, type AuthorizedEntityRow } from '../content/authorization';
import type { AppVariables, Env } from '../types';

type AppContext=Context<{Bindings:Env;Variables:AppVariables}>;
export const vaultRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();

interface EntityRow extends AuthorizedEntityRow {world_id:string|null;world_name:string|null;group_id:string|null;group_name:string|null;parent_entity_id:string|null;parent_name:string|null;entity_type:VaultEntityType;name:string;summary:string;description:string;created_at:string;updated_at:string;adventure_type:string|null;recommended_sessions:number|null;adventure_notes:string|null;campaign_count:number;owner_name:string}

function present(row:EntityRow,userId:string){const context=entityAccessContext(userId,row);return {id:row.id,ownerUserId:row.owner_user_id,ownerName:row.owner_name,worldId:row.world_id,worldName:row.world_name,groupId:row.group_id,groupName:row.group_name,parentEntityId:row.parent_entity_id,parentName:row.parent_name,entityType:row.entity_type,name:row.name,summary:row.summary,description:row.description,visibility:row.visibility,archivedAt:row.archived_at,createdAt:row.created_at,updatedAt:row.updated_at,campaignCount:Number(row.campaign_count),adventure:row.entity_type==='ADVENTURE'?{adventureType:row.adventure_type,recommendedSessions:row.recommended_sessions,notes:row.adventure_notes??''}:null,isOwner:row.owner_user_id===userId,permissions:{edit:canEditEntity(context),archive:canArchiveEntity(context),restore:canRestoreEntity(context),delete:canDeleteEntity(context)}};}

const SELECT=`SELECT e.*,w.name world_name,g.name group_name,p.name parent_name,u.display_name owner_name,
  a.adventure_type,a.recommended_sessions,a.notes adventure_notes,
  (SELECT COUNT(*) FROM campaign_entities ce WHERE ce.entity_id=e.id) campaign_count`;
const JOINS=`FROM vault_entities e JOIN users u ON u.id=e.owner_user_id LEFT JOIN worlds w ON w.id=e.world_id LEFT JOIN play_groups g ON g.id=e.group_id LEFT JOIN vault_entities p ON p.id=e.parent_entity_id LEFT JOIN adventure_details a ON a.entity_id=e.id`;

async function validateReferences(c:AppContext,input:VaultEntityInput,currentId:string|null){const userId=c.get('user').id;
  if(input.worldId){const world=await c.env.DB.prepare('SELECT id FROM worlds WHERE id=? AND owner_user_id=?').bind(input.worldId,userId).first();if(!world)throw new ApiError(422,'INVALID_WORLD','Mundo inválido.');}
  if(input.visibility==='GROUP'){if(!input.groupId)throw new ApiError(422,'GROUP_REQUIRED','A visibilidade de grupo exige um grupo.');const group=await c.env.DB.prepare('SELECT id FROM play_groups WHERE id=? AND user_id=?').bind(input.groupId,userId).first();if(!group)throw new ApiError(422,'INVALID_GROUP','Grupo inválido.');}else if(input.groupId)throw new ApiError(422,'UNEXPECTED_GROUP','Grupo só pode ser associado à visibilidade GROUP.');
  if(!validateAdventureDetails(input.entityType,input.adventure))throw new ApiError(422,'INVALID_ADVENTURE','Detalhes de Adventure incompatíveis com o tipo selecionado.');
  if(input.entityType!=='LOCATION'&&input.parentEntityId)throw new ApiError(422,'INVALID_LOCATION_PARENT','Somente locais podem possuir pai.');
  if(input.parentEntityId){const parent=await c.env.DB.prepare('SELECT id,entity_type entityType,world_id worldId FROM vault_entities WHERE id=? AND owner_user_id=?').bind(input.parentEntityId,userId).first<{id:string;entityType:VaultEntityType;worldId:string|null}>();if(!parent)throw new ApiError(422,'INVALID_LOCATION_PARENT','Local pai inválido.');if((parent.worldId??null)!==(input.worldId??null))throw new ApiError(422,'LOCATION_WORLD_MISMATCH','Local pai e filho precisam pertencer ao mesmo mundo.');const ancestors=await c.env.DB.prepare(`WITH RECURSIVE chain(id,parent_entity_id) AS (SELECT id,parent_entity_id FROM vault_entities WHERE id=? UNION ALL SELECT e.id,e.parent_entity_id FROM vault_entities e JOIN chain ON e.id=chain.parent_entity_id) SELECT id FROM chain`).bind(input.parentEntityId).all<{id:string}>();if(!validateLocationParent({entityId:currentId,entityType:input.entityType,parentId:input.parentEntityId,parentType:parent.entityType,parentAncestorIds:ancestors.results.map((item)=>item.id)}))throw new ApiError(422,'INVALID_LOCATION_PARENT','A hierarquia de locais é inválida ou cíclica.');}
}

vaultRoutes.get('/metadata',async(c)=>{const userId=c.get('user').id;const [worlds,groups,campaigns,locations]=await c.env.DB.batch([c.env.DB.prepare("SELECT id,name FROM worlds WHERE owner_user_id=? AND archived_at IS NULL ORDER BY name").bind(userId),c.env.DB.prepare('SELECT id,name FROM play_groups WHERE user_id=? ORDER BY name').bind(userId),c.env.DB.prepare("SELECT id,name FROM campaigns WHERE user_id=? ORDER BY name").bind(userId),c.env.DB.prepare("SELECT id,name,world_id worldId FROM vault_entities WHERE owner_user_id=? AND entity_type='LOCATION' AND archived_at IS NULL ORDER BY name").bind(userId)]);return c.json({worlds:worlds.results,groups:groups.results,campaigns:campaigns.results,locations:locations.results});});

vaultRoutes.get('/',async(c)=>{const userId=c.get('user').id,query=c.req.query();const page=Math.max(1,Number.parseInt(query.page??'1',10)||1),pageSize=Math.min(50,Math.max(1,Number.parseInt(query.pageSize??'18',10)||18));const archive=query.archive??'active';if(!['active','archived','all'].includes(archive))throw new ApiError(422,'INVALID_FILTER','Filtro de arquivo inválido.');const where=[entityAuthorizationPredicate()];const filterValues:unknown[]=[];if(archive==='active')where.push('e.archived_at IS NULL');else if(archive==='archived'){where.push('e.archived_at IS NOT NULL','e.owner_user_id=?');filterValues.push(userId);}if(query.type){if(!ENTITY_TYPES.includes(query.type as VaultEntityType))throw new ApiError(422,'INVALID_TYPE','Tipo de entidade inválido.');where.push('e.entity_type=?');filterValues.push(query.type);}if(query.worldId){where.push('e.world_id=?');filterValues.push(query.worldId);}if(query.visibility){if(!ENTITY_VISIBILITIES.includes(query.visibility as typeof ENTITY_VISIBILITIES[number]))throw new ApiError(422,'INVALID_VISIBILITY','Visibilidade inválida.');where.push('e.visibility=?');filterValues.push(query.visibility);}if(query.search){where.push("e.name LIKE ? ESCAPE '\\'");filterValues.push(`%${query.search.slice(0,100).replaceAll('\\','\\\\').replaceAll('%','\\%').replaceAll('_','\\_')}%`);}const orders:Record<string,string>={recent:'e.updated_at DESC',name:'e.name COLLATE NOCASE',oldest:'e.created_at'};if(query.sort&&!orders[query.sort])throw new ApiError(422,'INVALID_SORT','Ordenação inválida.');const authColumnsValues=[userId,userId,userId,userId],authWhereValues=entityAuthorizationValues(userId),clause=where.join(' AND ');const [rows,count]=await c.env.DB.batch([c.env.DB.prepare(`${SELECT},${entityAuthorizationColumns()} ${JOINS} WHERE ${clause} ORDER BY ${orders[query.sort??'recent']} LIMIT ? OFFSET ?`).bind(...authColumnsValues,...authWhereValues,...filterValues,pageSize,(page-1)*pageSize),c.env.DB.prepare(`SELECT COUNT(*) total FROM vault_entities e WHERE ${clause}`).bind(...authWhereValues,...filterValues)]);return c.json({items:(rows.results as unknown as EntityRow[]).map((row)=>present(row,userId)),pagination:{page,pageSize,total:Number((count.results[0] as {total:number}).total)}});});

vaultRoutes.post('/',async(c)=>{const input=await readJson(c,vaultEntityInputSchema);await validateReferences(c,input,null);const id=crypto.randomUUID(),now=nowIso(),userId=c.get('user').id;const statements:D1PreparedStatement[]=[c.env.DB.prepare(`INSERT INTO vault_entities (id,owner_user_id,world_id,group_id,parent_entity_id,entity_type,name,summary,description,visibility,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,userId,input.worldId??null,input.groupId??null,input.parentEntityId??null,input.entityType,input.name,input.summary,input.description,input.visibility,now,now)];if(input.adventure)statements.push(c.env.DB.prepare('INSERT INTO adventure_details (entity_id,adventure_type,recommended_sessions,notes) VALUES (?,?,?,?)').bind(id,input.adventure.adventureType,input.adventure.recommendedSessions,input.adventure.notes));await c.env.DB.batch(statements);return c.json({id},201);});

vaultRoutes.get('/:id',async(c)=>{await authorizedEntity(c,c.req.param('id'));const userId=c.get('user').id;const row=await c.env.DB.prepare(`${SELECT},${entityAuthorizationColumns()} ${JOINS} WHERE e.id=?`).bind(userId,userId,userId,userId,c.req.param('id')).first<EntityRow>();if(!row)throw new ApiError(404,'NOT_FOUND','Entidade não encontrada.');const campaigns=row.owner_user_id===userId?await c.env.DB.prepare(`SELECT c.id,c.name,r.title rpgTitle,ce.usage_type usageType FROM campaign_entities ce JOIN campaigns c ON c.id=ce.campaign_id JOIN rpgs r ON r.id=c.rpg_id WHERE ce.entity_id=? AND c.user_id=? ORDER BY c.name`).bind(row.id,userId).all():await c.env.DB.prepare(`SELECT DISTINCT c.id,c.name,r.title rpgTitle,ce.usage_type usageType FROM campaign_entities ce JOIN campaigns c ON c.id=ce.campaign_id JOIN rpgs r ON r.id=c.rpg_id JOIN campaign_members cm ON cm.campaign_id=c.id WHERE ce.entity_id=? AND cm.user_id=? ORDER BY c.name`).bind(row.id,userId).all();return c.json({item:present(row,userId),campaigns:campaigns.results});});

vaultRoutes.patch('/:id',async(c)=>{const current=await ownedEntity(c,c.req.param('id'));if(current.archived_at)throw new ApiError(409,'ENTITY_ARCHIVED','Restaure a entidade antes de editá-la.');const input=await readJson(c,vaultEntityInputSchema);await validateReferences(c,input,c.req.param('id'));const now=nowIso();const statements:D1PreparedStatement[]=[c.env.DB.prepare(`UPDATE vault_entities SET world_id=?,group_id=?,parent_entity_id=?,entity_type=?,name=?,summary=?,description=?,visibility=?,updated_at=? WHERE id=? AND owner_user_id=?`).bind(input.worldId??null,input.groupId??null,input.parentEntityId??null,input.entityType,input.name,input.summary,input.description,input.visibility,now,c.req.param('id'),c.get('user').id),c.env.DB.prepare('DELETE FROM adventure_details WHERE entity_id=?').bind(c.req.param('id'))];if(input.adventure)statements.push(c.env.DB.prepare('INSERT INTO adventure_details (entity_id,adventure_type,recommended_sessions,notes) VALUES (?,?,?,?)').bind(c.req.param('id'),input.adventure.adventureType,input.adventure.recommendedSessions,input.adventure.notes));await c.env.DB.batch(statements);return c.json({success:true});});

vaultRoutes.post('/:id/archive',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'));if(entity.archived_at)throw new ApiError(409,'ALREADY_ARCHIVED','A entidade já está arquivada.');const now=nowIso();await c.env.DB.prepare('UPDATE vault_entities SET archived_at=?,updated_at=? WHERE id=? AND owner_user_id=?').bind(now,now,c.req.param('id'),c.get('user').id).run();return c.json({success:true});});
vaultRoutes.post('/:id/restore',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'));if(!entity.archived_at)throw new ApiError(409,'NOT_ARCHIVED','A entidade não está arquivada.');await c.env.DB.prepare('UPDATE vault_entities SET archived_at=NULL,updated_at=? WHERE id=? AND owner_user_id=?').bind(nowIso(),c.req.param('id'),c.get('user').id).run();return c.json({success:true});});
vaultRoutes.delete('/:id',async(c)=>{await ownedEntity(c,c.req.param('id'));const dependency=await c.env.DB.prepare(`SELECT (SELECT COUNT(*) FROM campaign_entities WHERE entity_id=?) campaignLinks,(SELECT COUNT(*) FROM campaigns WHERE adventure_entity_id=?) primaryAdventure,(SELECT COUNT(*) FROM vault_entities WHERE parent_entity_id=?) children`).bind(c.req.param('id'),c.req.param('id'),c.req.param('id')).first<{campaignLinks:number;primaryAdventure:number;children:number}>();if(Number(dependency?.campaignLinks)||Number(dependency?.primaryAdventure)||Number(dependency?.children))throw new ApiError(409,'ENTITY_HAS_DEPENDENCIES','Arquive a entidade ou remova primeiro seus vínculos.');await c.env.DB.prepare('DELETE FROM vault_entities WHERE id=? AND owner_user_id=?').bind(c.req.param('id'),c.get('user').id).run();return c.body(null,204);});
