import { Hono, type Context } from 'hono';
import { canArchiveEntity, canDeleteEntity, canEditEntity, canRestoreEntity, resolveEntityVisibility } from '../../domain/content/permissions';
import { validateAdventureDetails, validateLocationParent, validateLoreDetails } from '../../domain/content/validation';
import { validateCreatureStatValues, validateSpecializedDetails } from '../../domain/content/specialized';
import { ENTITY_TYPES, ENTITY_VISIBILITIES, type AdventureType, type CreatureStatFieldDefinition, type LoreCanonStatus, type LoreType, type VaultEntityType } from '../../domain/content/types';
import { vaultEntityForkInputSchema, vaultEntityInputSchema, worldEntityLinkInputSchema, type VaultEntityInput } from '../../shared/validation/schemas';
import { ApiError, nowIso, readJson } from '../http';
import { authorizedEntity, entityAccessContext, entityAuthorizationColumns, entityAuthorizationPredicate, entityAuthorizationValues, ownedEntity, ownedWorld, worldEntityDiscoveryPredicate, type AuthorizedEntityRow } from '../content/authorization';
import { getRevision, listRevisions, parseRevisionNumber, parseSnapshot, recordRevisionStatement } from '../content/revisions';
import type { AppVariables, Env } from '../types';

export type AppContext=Context<{Bindings:Env;Variables:AppVariables}>;
export const vaultRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();

interface EntityRow extends AuthorizedEntityRow {world_id:string|null;world_name:string|null;group_id:string|null;group_name:string|null;parent_entity_id:string|null;parent_name:string|null;entity_type:VaultEntityType;name:string;summary:string;description:string;created_at:string;updated_at:string;adventure_type:string|null;recommended_sessions:number|null;adventure_notes:string|null;adventure_premise:string|null;adventure_hooks:string|null;adventure_key_scenes:string|null;adventure_rewards:string|null;lore_type:string|null;lore_canon_status:string|null;lore_source:string|null;campaign_count:number;owner_name:string;player_user_id:string|null;player_display_name:string|null;character_pronouns:string|null;character_concept:string|null;character_status:string|null;character_notes:string|null;npc_role:string|null;npc_occupation:string|null;npc_motivation:string|null;npc_public_notes:string|null;npc_gm_notes:string|null;creature_classification:string|null;creature_habitat:string|null;creature_behavior:string|null;creature_danger_notes:string|null;stat_template_id:string|null;stat_template_name:string|null;stat_field_definitions:string|null;stat_values_json:string|null;faction_purpose:string|null;faction_scope:string|null;faction_status:string|null;faction_public_description:string|null;faction_gm_notes:string|null;item_type:string|null;item_rarity:string|null;item_public_description:string|null;item_gm_notes:string|null}

function parseStoredJson<T>(value:string|null,fallback:T,context:string):T{if(!value)return fallback;try{return JSON.parse(value) as T;}catch(cause){throw new Error(`Invalid stored JSON for ${context}`,{cause});}}
function present(row:EntityRow,userId:string){const context=entityAccessContext(userId,row),access=resolveEntityVisibility(context),canSeeGmNotes=access==='OWNER'||access==='GAME_MASTER';return {id:row.id,ownerUserId:row.owner_user_id,ownerName:row.owner_name,worldId:row.world_id,worldName:row.world_name,groupId:row.group_id,groupName:row.group_name,parentEntityId:row.parent_entity_id,parentName:row.parent_name,entityType:row.entity_type,name:row.name,summary:row.summary,description:row.description,visibility:row.visibility,archivedAt:row.archived_at,createdAt:row.created_at,updatedAt:row.updated_at,campaignCount:Number(row.campaign_count),adventure:row.entity_type==='ADVENTURE'?{adventureType:row.adventure_type,recommendedSessions:row.recommended_sessions,notes:row.adventure_notes??'',premise:row.adventure_premise??'',hooks:row.adventure_hooks??'',keyScenes:row.adventure_key_scenes??'',rewards:row.adventure_rewards??''}:null,lore:row.entity_type==='LORE'?{loreType:row.lore_type,canonStatus:row.lore_canon_status,source:row.lore_source??''}:null,character:row.entity_type==='CHARACTER'?{playerUserId:row.player_user_id,playerDisplayName:row.player_display_name,pronouns:row.character_pronouns??'',concept:row.character_concept??'',status:row.character_status??'',notes:row.character_notes??''}:null,npc:row.entity_type==='NPC'?{role:row.npc_role??'',occupation:row.npc_occupation??'',motivation:row.npc_motivation??'',publicNotes:row.npc_public_notes??'',...(canSeeGmNotes?{gmNotes:row.npc_gm_notes??''}:{})}:null,creature:row.entity_type==='CREATURE'?{classification:row.creature_classification??'',habitat:row.creature_habitat??'',behavior:row.creature_behavior??'',dangerNotes:row.creature_danger_notes??'',statBlock:row.stat_template_id?{templateId:row.stat_template_id,templateName:row.stat_template_name,fields:parseStoredJson(row.stat_field_definitions,[],`template ${row.stat_template_id}`),values:parseStoredJson(row.stat_values_json,{},`creature ${row.id}`)}:null}:null,faction:row.entity_type==='FACTION'?{purpose:row.faction_purpose??'',scope:row.faction_scope??'',status:row.faction_status??'',publicDescription:row.faction_public_description??'',...(canSeeGmNotes?{gmNotes:row.faction_gm_notes??''}:{})}:null,item:row.entity_type==='ITEM'?{itemType:row.item_type??'',rarity:row.item_rarity??'',publicDescription:row.item_public_description??'',...(canSeeGmNotes?{gmNotes:row.item_gm_notes??''}:{})}:null,isOwner:row.owner_user_id===userId,permissions:{edit:canEditEntity(context),archive:canArchiveEntity(context),restore:canRestoreEntity(context),delete:canDeleteEntity(context)}};}

const SELECT=`SELECT e.*,w.name world_name,g.name group_name,p.name parent_name,u.display_name owner_name,
  a.adventure_type,a.recommended_sessions,a.notes adventure_notes,a.premise adventure_premise,a.hooks adventure_hooks,a.key_scenes adventure_key_scenes,a.rewards adventure_rewards,
  l.lore_type,l.canon_status lore_canon_status,l.source lore_source,
  ch.player_user_id,pu.display_name player_display_name,ch.pronouns character_pronouns,ch.concept character_concept,ch.status character_status,ch.notes character_notes,
  n.role npc_role,n.occupation npc_occupation,n.motivation npc_motivation,n.public_notes npc_public_notes,n.gm_notes npc_gm_notes,
  cr.classification creature_classification,cr.habitat creature_habitat,cr.behavior creature_behavior,cr.danger_notes creature_danger_notes,
  sb.template_id stat_template_id,st.name stat_template_name,st.field_definitions stat_field_definitions,sb.values_json stat_values_json,
  f.purpose faction_purpose,f.scope faction_scope,f.status faction_status,f.public_description faction_public_description,f.gm_notes faction_gm_notes,
  i.item_type,i.rarity item_rarity,i.public_description item_public_description,i.gm_notes item_gm_notes,
  (SELECT COUNT(*) FROM campaign_entities ce WHERE ce.entity_id=e.id) campaign_count`;
const JOINS=`FROM vault_entities e JOIN users u ON u.id=e.owner_user_id LEFT JOIN worlds w ON w.id=e.world_id LEFT JOIN play_groups g ON g.id=e.group_id LEFT JOIN vault_entities p ON p.id=e.parent_entity_id LEFT JOIN adventure_details a ON a.entity_id=e.id LEFT JOIN lore_details l ON l.entity_id=e.id LEFT JOIN character_details ch ON ch.entity_id=e.id LEFT JOIN users pu ON pu.id=ch.player_user_id LEFT JOIN npc_details n ON n.entity_id=e.id LEFT JOIN creature_details cr ON cr.entity_id=e.id LEFT JOIN creature_stat_blocks sb ON sb.entity_id=e.id LEFT JOIN creature_stat_templates st ON st.id=sb.template_id LEFT JOIN faction_details f ON f.entity_id=e.id LEFT JOIN item_details i ON i.entity_id=e.id`;

async function validateReferences(c:AppContext,input:VaultEntityInput,currentId:string|null){const userId=c.get('user').id;
  if(input.worldId){const world=await c.env.DB.prepare('SELECT id FROM worlds WHERE id=? AND owner_user_id=?').bind(input.worldId,userId).first();if(!world)throw new ApiError(422,'INVALID_WORLD','Mundo inválido.');}
  if(input.visibility==='GROUP'){if(!input.groupId)throw new ApiError(422,'GROUP_REQUIRED','A visibilidade de grupo exige um grupo.');const group=await c.env.DB.prepare('SELECT id FROM play_groups WHERE id=? AND user_id=?').bind(input.groupId,userId).first();if(!group)throw new ApiError(422,'INVALID_GROUP','Grupo inválido.');}else if(input.groupId)throw new ApiError(422,'UNEXPECTED_GROUP','Grupo só pode ser associado à visibilidade GROUP.');
  if(!validateAdventureDetails(input.entityType,input.adventure))throw new ApiError(422,'INVALID_ADVENTURE','Detalhes de Adventure incompatíveis com o tipo selecionado.');
  if(!validateLoreDetails(input.entityType,input.lore))throw new ApiError(422,'INVALID_LORE','Detalhes de Lore incompatíveis com o tipo selecionado.');
  if(!validateSpecializedDetails(input.entityType,{character:input.character,npc:input.npc,creature:input.creature,faction:input.faction,item:input.item}))throw new ApiError(422,'INVALID_SPECIALIZED_DETAILS','Os campos especializados não correspondem ao tipo da entidade.');
  if(input.character?.playerUserId){const player=await c.env.DB.prepare('SELECT id FROM users WHERE id=? AND disabled_at IS NULL AND deleted_at IS NULL').bind(input.character.playerUserId).first();if(!player)throw new ApiError(422,'INVALID_PLAYER','A conta de jogador selecionada não está disponível.');}
  if(input.creature?.statBlock){if(!input.worldId)throw new ApiError(422,'CREATURE_WORLD_REQUIRED','Uma ficha de criatura exige que a entidade pertença a um World.');const template=await c.env.DB.prepare('SELECT field_definitions FROM creature_stat_templates WHERE id=? AND world_id=? AND owner_user_id=?').bind(input.creature.statBlock.templateId,input.worldId,userId).first<{field_definitions:string}>();if(!template)throw new ApiError(422,'INVALID_STAT_TEMPLATE','Modelo de estatísticas inválido para este World.');const fields=parseStoredJson<CreatureStatFieldDefinition[]>(template.field_definitions,[],`template ${input.creature.statBlock.templateId}`);if(!validateCreatureStatValues(fields,input.creature.statBlock.values))throw new ApiError(422,'INVALID_STAT_VALUES','Os valores da ficha não correspondem ao modelo selecionado.');}
  if(input.entityType!=='LOCATION'&&input.parentEntityId)throw new ApiError(422,'INVALID_LOCATION_PARENT','Somente locais podem possuir pai.');
  if(input.parentEntityId){const parent=await c.env.DB.prepare('SELECT id,entity_type entityType,world_id worldId FROM vault_entities WHERE id=? AND owner_user_id=?').bind(input.parentEntityId,userId).first<{id:string;entityType:VaultEntityType;worldId:string|null}>();if(!parent)throw new ApiError(422,'INVALID_LOCATION_PARENT','Local pai inválido.');if((parent.worldId??null)!==(input.worldId??null))throw new ApiError(422,'LOCATION_WORLD_MISMATCH','Local pai e filho precisam pertencer ao mesmo mundo.');const ancestors=await c.env.DB.prepare(`WITH RECURSIVE chain(id,parent_entity_id) AS (SELECT id,parent_entity_id FROM vault_entities WHERE id=? UNION ALL SELECT e.id,e.parent_entity_id FROM vault_entities e JOIN chain ON e.id=chain.parent_entity_id) SELECT id FROM chain`).bind(input.parentEntityId).all<{id:string}>();if(!validateLocationParent({entityId:currentId,entityType:input.entityType,parentId:input.parentEntityId,parentType:parent.entityType,parentAncestorIds:ancestors.results.map((item)=>item.id)}))throw new ApiError(422,'INVALID_LOCATION_PARENT','A hierarquia de locais é inválida ou cíclica.');}
}

// F-015: exportada para reuso em src/server/routes/backup-restore.ts — restaurar uma
// entidade escreve os mesmos campos especializados de um create normal, nunca um
// caminho paralelo (mesmo princípio já aplicado a buildEntityUpdateStatements/restore
// de revisão).
export function specializedStatements(c:AppContext,input:VaultEntityInput,entityId:string):D1PreparedStatement[]{const statements:D1PreparedStatement[]=[];
  if(input.entityType==='CHARACTER'){const value=input.character??{playerUserId:null,pronouns:'',concept:'',status:'',notes:''};statements.push(c.env.DB.prepare('INSERT INTO character_details (entity_id,player_user_id,pronouns,concept,status,notes) VALUES (?,?,?,?,?,?)').bind(entityId,value.playerUserId,value.pronouns,value.concept,value.status,value.notes));}
  if(input.entityType==='NPC'){const value=input.npc??{role:'',occupation:'',motivation:'',publicNotes:'',gmNotes:''};statements.push(c.env.DB.prepare('INSERT INTO npc_details (entity_id,role,occupation,motivation,public_notes,gm_notes) VALUES (?,?,?,?,?,?)').bind(entityId,value.role,value.occupation,value.motivation,value.publicNotes,value.gmNotes));}
  if(input.entityType==='CREATURE'){const value=input.creature??{classification:'',habitat:'',behavior:'',dangerNotes:'',statBlock:null};statements.push(c.env.DB.prepare('INSERT INTO creature_details (entity_id,classification,habitat,behavior,danger_notes) VALUES (?,?,?,?,?)').bind(entityId,value.classification,value.habitat,value.behavior,value.dangerNotes));if(value.statBlock)statements.push(c.env.DB.prepare('INSERT INTO creature_stat_blocks (entity_id,template_id,values_json) VALUES (?,?,?)').bind(entityId,value.statBlock.templateId,JSON.stringify(value.statBlock.values)));}
  if(input.entityType==='FACTION'){const value=input.faction??{purpose:'',scope:'',status:'',publicDescription:'',gmNotes:''};statements.push(c.env.DB.prepare('INSERT INTO faction_details (entity_id,purpose,scope,status,public_description,gm_notes) VALUES (?,?,?,?,?,?)').bind(entityId,value.purpose,value.scope,value.status,value.publicDescription,value.gmNotes));}
  if(input.entityType==='ITEM'){const value=input.item??{itemType:'',rarity:'',publicDescription:'',gmNotes:''};statements.push(c.env.DB.prepare('INSERT INTO item_details (entity_id,item_type,rarity,public_description,gm_notes) VALUES (?,?,?,?,?)').bind(entityId,value.itemType,value.rarity,value.publicDescription,value.gmNotes));}
  return statements;
}

vaultRoutes.get('/metadata',async(c)=>{const userId=c.get('user').id;const [worlds,groups,campaigns,locations]=await c.env.DB.batch([c.env.DB.prepare("SELECT id,name FROM worlds WHERE owner_user_id=? AND archived_at IS NULL ORDER BY name").bind(userId),c.env.DB.prepare('SELECT id,name FROM play_groups WHERE user_id=? ORDER BY name').bind(userId),c.env.DB.prepare("SELECT id,name FROM campaigns WHERE user_id=? ORDER BY name").bind(userId),c.env.DB.prepare("SELECT id,name,world_id worldId FROM vault_entities WHERE owner_user_id=? AND entity_type='LOCATION' AND archived_at IS NULL ORDER BY name").bind(userId)]);return c.json({worlds:worlds.results,groups:groups.results,campaigns:campaigns.results,locations:locations.results});});

vaultRoutes.get('/',async(c)=>{const userId=c.get('user').id,query=c.req.query();const page=Math.max(1,Number.parseInt(query.page??'1',10)||1),pageSize=Math.min(50,Math.max(1,Number.parseInt(query.pageSize??'18',10)||18));const archive=query.archive??'active';if(!['active','archived','all'].includes(archive))throw new ApiError(422,'INVALID_FILTER','Filtro de arquivo inválido.');const where=[entityAuthorizationPredicate()];const filterValues:unknown[]=[];if(archive==='active')where.push('e.archived_at IS NULL');else if(archive==='archived'){where.push('e.archived_at IS NOT NULL','e.owner_user_id=?');filterValues.push(userId);}if(query.type){if(!ENTITY_TYPES.includes(query.type as VaultEntityType))throw new ApiError(422,'INVALID_TYPE','Tipo de entidade inválido.');where.push('e.entity_type=?');filterValues.push(query.type);}if(query.worldId){where.push(worldEntityDiscoveryPredicate());filterValues.push(query.worldId,query.worldId);}if(query.visibility){if(!ENTITY_VISIBILITIES.includes(query.visibility as typeof ENTITY_VISIBILITIES[number]))throw new ApiError(422,'INVALID_VISIBILITY','Visibilidade inválida.');where.push('e.visibility=?');filterValues.push(query.visibility);}if(query.search){where.push("e.name LIKE ? ESCAPE '\\'");filterValues.push(`%${query.search.slice(0,100).replaceAll('\\','\\\\').replaceAll('%','\\%').replaceAll('_','\\_')}%`);}const orders:Record<string,string>={recent:'e.updated_at DESC',name:'e.name COLLATE NOCASE',oldest:'e.created_at'};if(query.sort&&!orders[query.sort])throw new ApiError(422,'INVALID_SORT','Ordenação inválida.');const authColumnsValues=[userId,userId,userId,userId],authWhereValues=entityAuthorizationValues(userId),clause=where.join(' AND ');const [rows,count]=await c.env.DB.batch([c.env.DB.prepare(`${SELECT},${entityAuthorizationColumns()} ${JOINS} WHERE ${clause} ORDER BY ${orders[query.sort??'recent']} LIMIT ? OFFSET ?`).bind(...authColumnsValues,...authWhereValues,...filterValues,pageSize,(page-1)*pageSize),c.env.DB.prepare(`SELECT COUNT(*) total FROM vault_entities e WHERE ${clause}`).bind(...authWhereValues,...filterValues)]);return c.json({items:(rows.results as unknown as EntityRow[]).map((row)=>present(row,userId)),pagination:{page,pageSize,total:Number((count.results[0] as {total:number}).total)}});});

// F-022 (BATCH12): extraído do POST / para ser reaproveitado pelo FORK (POST /:id/fork) —
// um fork É um create normal (mesmo caminho de escrita/validação), nunca um segundo
// caminho paralelo, mesmo princípio já aplicado a buildEntityUpdateStatements.
function buildEntityCreateStatements(c:AppContext,input:VaultEntityInput,id:string,now:string,userId:string):D1PreparedStatement[]{
  const statements:D1PreparedStatement[]=[c.env.DB.prepare(`INSERT INTO vault_entities (id,owner_user_id,world_id,group_id,parent_entity_id,entity_type,name,summary,description,visibility,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,userId,input.worldId??null,input.groupId??null,input.parentEntityId??null,input.entityType,input.name,input.summary,input.description,input.visibility,now,now)];
  if(input.adventure)statements.push(c.env.DB.prepare('INSERT INTO adventure_details (entity_id,adventure_type,recommended_sessions,notes,premise,hooks,key_scenes,rewards) VALUES (?,?,?,?,?,?,?,?)').bind(id,input.adventure.adventureType,input.adventure.recommendedSessions,input.adventure.notes,input.adventure.premise,input.adventure.hooks,input.adventure.keyScenes,input.adventure.rewards));
  if(input.entityType==='LORE'){const lore=input.lore??{loreType:'CUSTOM',canonStatus:'DRAFT',source:''};statements.push(c.env.DB.prepare('INSERT INTO lore_details (entity_id,lore_type,canon_status,source) VALUES (?,?,?,?)').bind(id,lore.loreType,lore.canonStatus,lore.source));}
  statements.push(...specializedStatements(c,input,id));
  return statements;
}

vaultRoutes.post('/',async(c)=>{const input=await readJson(c,vaultEntityInputSchema);await validateReferences(c,input,null);const id=crypto.randomUUID(),now=nowIso(),userId=c.get('user').id;
  const statements=buildEntityCreateStatements(c,input,id,now,userId);
  // F-001: revisão inicial — mesma transação do create, nunca um passo separado que possa falhar sozinho.
  statements.push(recordRevisionStatement(c.env.DB,{resourceType:'VAULT_ENTITY',resourceId:id,ownerUserId:userId,actorUserId:userId,action:'CREATE',snapshot:input,now}));
  await c.env.DB.batch(statements);return c.json({id},201);});

vaultRoutes.get('/:id',async(c)=>{await authorizedEntity(c,c.req.param('id'));const userId=c.get('user').id;const row=await c.env.DB.prepare(`${SELECT},${entityAuthorizationColumns()} ${JOINS} WHERE e.id=?`).bind(userId,userId,userId,userId,c.req.param('id')).first<EntityRow>();if(!row)throw new ApiError(404,'NOT_FOUND','Entidade não encontrada.');const campaigns=row.owner_user_id===userId?await c.env.DB.prepare(`SELECT c.id,c.name,r.title rpgTitle,ce.usage_type usageType,(c.adventure_entity_id=ce.entity_id) isPrimary FROM campaign_entities ce JOIN campaigns c ON c.id=ce.campaign_id JOIN rpgs r ON r.id=c.rpg_id WHERE ce.entity_id=? AND c.user_id=? ORDER BY c.name`).bind(row.id,userId).all():await c.env.DB.prepare(`SELECT DISTINCT c.id,c.name,r.title rpgTitle,ce.usage_type usageType,(c.adventure_entity_id=ce.entity_id) isPrimary FROM campaign_entities ce JOIN campaigns c ON c.id=ce.campaign_id JOIN rpgs r ON r.id=c.rpg_id JOIN campaign_members cm ON cm.campaign_id=c.id WHERE ce.entity_id=? AND cm.user_id=? ORDER BY c.name`).bind(row.id,userId).all();return c.json({item:present(row,userId),campaigns:campaigns.results});});

// F-001: extraído do PATCH para ser reaproveitado pelo restore de revisão — restaurar É editar
// (mesma validação, mesma escrita), nunca um caminho paralelo.
function buildEntityUpdateStatements(c:AppContext,entityId:string,ownerUserId:string,input:VaultEntityInput,now:string):D1PreparedStatement[]{
  const statements:D1PreparedStatement[]=[c.env.DB.prepare(`UPDATE vault_entities SET world_id=?,group_id=?,parent_entity_id=?,entity_type=?,name=?,summary=?,description=?,visibility=?,updated_at=? WHERE id=? AND owner_user_id=?`).bind(input.worldId??null,input.groupId??null,input.parentEntityId??null,input.entityType,input.name,input.summary,input.description,input.visibility,now,entityId,ownerUserId),c.env.DB.prepare('DELETE FROM adventure_details WHERE entity_id=?').bind(entityId),c.env.DB.prepare('DELETE FROM lore_details WHERE entity_id=?').bind(entityId),c.env.DB.prepare('DELETE FROM character_details WHERE entity_id=?').bind(entityId),c.env.DB.prepare('DELETE FROM npc_details WHERE entity_id=?').bind(entityId),c.env.DB.prepare('DELETE FROM creature_stat_blocks WHERE entity_id=?').bind(entityId),c.env.DB.prepare('DELETE FROM creature_details WHERE entity_id=?').bind(entityId),c.env.DB.prepare('DELETE FROM faction_details WHERE entity_id=?').bind(entityId),c.env.DB.prepare('DELETE FROM item_details WHERE entity_id=?').bind(entityId)];
  if(input.adventure)statements.push(c.env.DB.prepare('INSERT INTO adventure_details (entity_id,adventure_type,recommended_sessions,notes,premise,hooks,key_scenes,rewards) VALUES (?,?,?,?,?,?,?,?)').bind(entityId,input.adventure.adventureType,input.adventure.recommendedSessions,input.adventure.notes,input.adventure.premise,input.adventure.hooks,input.adventure.keyScenes,input.adventure.rewards));
  if(input.entityType==='LORE'){const lore=input.lore??{loreType:'CUSTOM',canonStatus:'DRAFT',source:''};statements.push(c.env.DB.prepare('INSERT INTO lore_details (entity_id,lore_type,canon_status,source) VALUES (?,?,?,?)').bind(entityId,lore.loreType,lore.canonStatus,lore.source));}
  statements.push(...specializedStatements(c,input,entityId));
  return statements;
}

vaultRoutes.patch('/:id',async(c)=>{const current=await ownedEntity(c,c.req.param('id'));if(current.archived_at)throw new ApiError(409,'ENTITY_ARCHIVED','Restaure a entidade antes de editá-la.');const input=await readJson(c,vaultEntityInputSchema);const entityId=c.req.param('id');await validateReferences(c,input,entityId);const now=nowIso();
  const statements=buildEntityUpdateStatements(c,entityId,current.owner_user_id,input,now);
  statements.push(recordRevisionStatement(c.env.DB,{resourceType:'VAULT_ENTITY',resourceId:entityId,ownerUserId:current.owner_user_id,actorUserId:c.get('user').id,action:'UPDATE',snapshot:input,now}));
  await c.env.DB.batch(statements);return c.json({success:true});});

// F-001: histórico é owner-only, mesmo limite de acesso da edição (ownedEntity) — nunca o mesmo
// acesso "de leitura" mais amplo de authorizedEntity (que inclui jogadores/GM de campanha por
// visibilidade). Ver docs/product/RPG_MANAGER_FINAL_STATUS.md, seção F-001 "Autorização": edição
// já é exclusiva do dono neste produto (não existe co-edição), então histórico — que só existe
// por causa de edições — herda naturalmente o mesmo limite, sem criar um novo canal de acesso.
vaultRoutes.get('/:id/revisions',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'));const query=c.req.query();const page=Math.max(1,Number.parseInt(query.page??'1',10)||1);const pageSize=Math.min(50,Math.max(1,Number.parseInt(query.pageSize??'20',10)||20));const result=await listRevisions(c.env.DB,'VAULT_ENTITY',entity.id,page,pageSize);return c.json({items:result.items,pagination:{page,pageSize,total:result.total}});});

vaultRoutes.get('/:id/revisions/:number',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'));const number=parseRevisionNumber(c.req.param('number'));const row=await getRevision(c.env.DB,'VAULT_ENTITY',entity.id,number);if(!row)throw new ApiError(404,'NOT_FOUND','Revisão não encontrada.');return c.json({item:{...row,snapshot:JSON.parse(row.snapshotRaw)}});});

vaultRoutes.post('/:id/revisions/:number/restore',async(c)=>{const current=await ownedEntity(c,c.req.param('id'));if(current.archived_at)throw new ApiError(409,'ENTITY_ARCHIVED','Restaure a entidade antes de restaurar uma revisão.');const entityId=c.req.param('id');const number=parseRevisionNumber(c.req.param('number'));const revisionRow=await getRevision(c.env.DB,'VAULT_ENTITY',entityId,number);if(!revisionRow)throw new ApiError(404,'NOT_FOUND','Revisão não encontrada.');const input=parseSnapshot(vaultEntityInputSchema,revisionRow.snapshotRaw);await validateReferences(c,input,entityId);const now=nowIso();
  const statements=buildEntityUpdateStatements(c,entityId,current.owner_user_id,input,now);
  statements.push(recordRevisionStatement(c.env.DB,{resourceType:'VAULT_ENTITY',resourceId:entityId,ownerUserId:current.owner_user_id,actorUserId:c.get('user').id,action:'RESTORE',snapshot:input,restoredFromRevisionNumber:number,now}));
  await c.env.DB.batch(statements);return c.json({success:true});});

vaultRoutes.post('/:id/archive',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'));if(entity.archived_at)throw new ApiError(409,'ALREADY_ARCHIVED','A entidade já está arquivada.');const now=nowIso();await c.env.DB.prepare('UPDATE vault_entities SET archived_at=?,updated_at=? WHERE id=? AND owner_user_id=?').bind(now,now,c.req.param('id'),c.get('user').id).run();return c.json({success:true});});
vaultRoutes.post('/:id/restore',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'));if(!entity.archived_at)throw new ApiError(409,'NOT_ARCHIVED','A entidade não está arquivada.');await c.env.DB.prepare('UPDATE vault_entities SET archived_at=NULL,updated_at=? WHERE id=? AND owner_user_id=?').bind(nowIso(),c.req.param('id'),c.get('user').id).run();return c.json({success:true});});
vaultRoutes.delete('/:id',async(c)=>{await ownedEntity(c,c.req.param('id'));const dependency=await c.env.DB.prepare(`SELECT (SELECT COUNT(*) FROM campaign_entities WHERE entity_id=?) campaignLinks,(SELECT COUNT(*) FROM campaigns WHERE adventure_entity_id=?) primaryAdventure,(SELECT COUNT(*) FROM vault_entities WHERE parent_entity_id=?) children`).bind(c.req.param('id'),c.req.param('id'),c.req.param('id')).first<{campaignLinks:number;primaryAdventure:number;children:number}>();if(Number(dependency?.campaignLinks)||Number(dependency?.primaryAdventure)||Number(dependency?.children))throw new ApiError(409,'ENTITY_HAS_DEPENDENCIES','Arquive a entidade ou remova primeiro seus vínculos.');await c.env.DB.prepare('DELETE FROM vault_entities WHERE id=? AND owner_user_id=?').bind(c.req.param('id'),c.get('user').id).run();return c.body(null,204);});

// F-022 (BATCH12): Vault avançado — LINK (world_entity_links) nunca altera world_id nem
// autorização, só amplia em quais Worlds a entidade é descoberta (Wiki/Vault filtrado por
// World/busca — ver worldEntityDiscoveryPredicate). Owner-only (mesmo limite de "sem
// co-edição" de todo o domínio Vault): só quem é dono da entidade E do World de destino
// pode criar/remover um link — nunca cross-account.
vaultRoutes.get('/:id/links',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'));const rows=await c.env.DB.prepare('SELECT wel.world_id worldId,w.name worldName FROM world_entity_links wel JOIN worlds w ON w.id=wel.world_id WHERE wel.entity_id=? ORDER BY w.name COLLATE NOCASE').bind(entity.id).all();return c.json({items:rows.results});});

vaultRoutes.post('/:id/links',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'))as EntityRow;const input=await readJson(c,worldEntityLinkInputSchema);await ownedWorld(c,input.worldId);if(input.worldId===entity.world_id)throw new ApiError(422,'ALREADY_OWNING_WORLD','Esta entidade já pertence a este World.');await c.env.DB.prepare('INSERT OR IGNORE INTO world_entity_links (world_id,entity_id,created_at) VALUES (?,?,?)').bind(input.worldId,entity.id,nowIso()).run();return c.json({success:true},201);});

vaultRoutes.delete('/:id/links/:worldId',async(c)=>{const entity=await ownedEntity(c,c.req.param('id'));await c.env.DB.prepare('DELETE FROM world_entity_links WHERE world_id=? AND entity_id=?').bind(c.req.param('worldId'),entity.id).run();return c.body(null,204);});

// F-022: FORK (COPY) explícito — cria uma entidade NOVA e independente (nunca sincroniza
// de volta com a original). Reaproveita buildEntityCreateStatements/validateReferences —
// um fork É um create normal, só com os valores iniciais vindos da entidade de origem em
// vez de um formulário em branco. Nunca copia parentEntityId (hierarquia de Location fica
// presa ao World de origem — evitar ciclos/inconsistência entre World de origem e destino)
// nem o vínculo de ficha de criatura (statBlock referencia um template de um World
// específico, que pode não existir/ser diferente no World de destino).
vaultRoutes.post('/:id/fork',async(c)=>{
  const source=await ownedEntity(c,c.req.param('id'));
  const row=await c.env.DB.prepare(`${SELECT} ${JOINS} WHERE e.id=?`).bind(source.id).first<EntityRow>();
  if(!row)throw new ApiError(404,'NOT_FOUND','Entidade não encontrada.');
  const overrides=await readJson(c,vaultEntityForkInputSchema);
  const visibility=overrides.visibility??(row.visibility as typeof ENTITY_VISIBILITIES[number]);
  const input:VaultEntityInput={
    entityType:row.entity_type,
    name:overrides.name??`${row.name} (cópia)`,
    summary:row.summary,description:row.description,visibility,
    worldId:overrides.worldId!==undefined?overrides.worldId:row.world_id,
    groupId:overrides.groupId!==undefined?overrides.groupId:(visibility==='GROUP'?row.group_id:null),
    parentEntityId:null,
    adventure:row.entity_type==='ADVENTURE'?{adventureType:row.adventure_type as AdventureType,recommendedSessions:row.recommended_sessions,notes:row.adventure_notes??'',premise:row.adventure_premise??'',hooks:row.adventure_hooks??'',keyScenes:row.adventure_key_scenes??'',rewards:row.adventure_rewards??''}:null,
    lore:row.entity_type==='LORE'?{loreType:row.lore_type as LoreType,canonStatus:row.lore_canon_status as LoreCanonStatus,source:row.lore_source??''}:null,
    character:row.entity_type==='CHARACTER'?{playerUserId:row.player_user_id,pronouns:row.character_pronouns??'',concept:row.character_concept??'',status:row.character_status??'',notes:row.character_notes??''}:null,
    npc:row.entity_type==='NPC'?{role:row.npc_role??'',occupation:row.npc_occupation??'',motivation:row.npc_motivation??'',publicNotes:row.npc_public_notes??'',gmNotes:row.npc_gm_notes??''}:null,
    creature:row.entity_type==='CREATURE'?{classification:row.creature_classification??'',habitat:row.creature_habitat??'',behavior:row.creature_behavior??'',dangerNotes:row.creature_danger_notes??'',statBlock:null}:null,
    faction:row.entity_type==='FACTION'?{purpose:row.faction_purpose??'',scope:row.faction_scope??'',status:row.faction_status??'',publicDescription:row.faction_public_description??'',gmNotes:row.faction_gm_notes??''}:null,
    item:row.entity_type==='ITEM'?{itemType:row.item_type??'',rarity:row.item_rarity??'',publicDescription:row.item_public_description??'',gmNotes:row.item_gm_notes??''}:null,
  };
  await validateReferences(c,input,null);
  const id=crypto.randomUUID(),now=nowIso(),userId=c.get('user').id;
  const statements=buildEntityCreateStatements(c,input,id,now,userId);
  statements.push(recordRevisionStatement(c.env.DB,{resourceType:'VAULT_ENTITY',resourceId:id,ownerUserId:userId,actorUserId:userId,action:'CREATE',snapshot:input,now}));
  await c.env.DB.batch(statements);
  return c.json({id},201);
});
