import { Hono } from 'hono';
import { createWorldSlug } from '../../domain/content/validation';
import { worldInputSchema, worldMemberInputSchema } from '../../shared/validation/schemas';
import { ApiError, nowIso, readJson } from '../http';
import { authorizedWorld, entityAuthorizationColumns, entityAuthorizationPredicate, entityAuthorizationValues, ownedWorld, type AuthorizedWorldRow } from '../content/authorization';
import type { AppVariables, Env } from '../types';

export const worldRoutes = new Hono<{ Bindings: Env; Variables: AppVariables }>();

interface WorldRow extends AuthorizedWorldRow { name:string;slug:string;description:string;default_rpg_id:string|null;default_rpg_title:string|null;status:'ACTIVE'|'ARCHIVED';created_at:string;updated_at:string }

function present(row: WorldRow,userId:string){return {id:row.id,name:row.name,slug:row.slug,description:row.description,defaultRpgId:row.default_rpg_id,defaultRpgTitle:row.default_rpg_title,visibility:row.visibility,status:row.status,archivedAt:row.archived_at,createdAt:row.created_at,updatedAt:row.updated_at,isOwner:row.owner_user_id===userId};}

async function uniqueSlug(env:Env,ownerUserId:string,name:string,currentId?:string):Promise<string>{
  const base=createWorldSlug(name);for(let suffix=0;suffix<1000;suffix+=1){const slug=suffix?`${base.slice(0,Math.max(1,76-String(suffix).length))}-${suffix+1}`:base;const row=await env.DB.prepare('SELECT id FROM worlds WHERE owner_user_id=? AND slug=? AND (? IS NULL OR id<>?)').bind(ownerUserId,slug,currentId??null,currentId??null).first();if(!row)return slug;}throw new ApiError(409,'WORLD_SLUG_CONFLICT','Não foi possível gerar um endereço único para este mundo.');
}

async function validateDefaultRpg(env:Env,userId:string,rpgId:string|null|undefined){if(!rpgId)return;const row=await env.DB.prepare('SELECT id FROM rpgs WHERE id=? AND user_id=?').bind(rpgId,userId).first();if(!row)throw new ApiError(422,'INVALID_DEFAULT_RPG','RPG padrão inválido.');}

worldRoutes.get('/',async(c)=>{const userId=c.get('user').id;const query=c.req.query();const page=Math.max(1,Number.parseInt(query.page??'1',10)||1);const pageSize=Math.min(50,Math.max(1,Number.parseInt(query.pageSize??'12',10)||12));const archive=query.archive??'active';if(!['active','archived','all'].includes(archive))throw new ApiError(422,'INVALID_FILTER','Filtro de arquivo inválido.');const where=[`(w.owner_user_id=? OR (w.archived_at IS NULL AND w.visibility='GROUP' AND EXISTS(SELECT 1 FROM world_members wm WHERE wm.world_id=w.id AND wm.user_id=?)))`];const values:unknown[]=[userId,userId];if(archive==='active')where.push('w.archived_at IS NULL');else if(archive==='archived'){where.push('w.archived_at IS NOT NULL','w.owner_user_id=?');values.push(userId);}if(query.search){where.push("w.name LIKE ? ESCAPE '\\'");values.push(`%${query.search.slice(0,100).replaceAll('\\','\\\\').replaceAll('%','\\%').replaceAll('_','\\_')}%`);}const order:Record<string,string>={recent:'w.updated_at DESC',name:'w.name COLLATE NOCASE',oldest:'w.created_at'};if(query.sort&&!order[query.sort])throw new ApiError(422,'INVALID_SORT','Ordenação inválida.');const clause=where.join(' AND ');const [rows,count]=await c.env.DB.batch([c.env.DB.prepare(`SELECT w.*,r.title default_rpg_title,EXISTS(SELECT 1 FROM world_members wm WHERE wm.world_id=w.id AND wm.user_id=?) is_world_member FROM worlds w LEFT JOIN rpgs r ON r.id=w.default_rpg_id WHERE ${clause} ORDER BY ${order[query.sort??'recent']} LIMIT ? OFFSET ?`).bind(userId,...values,pageSize,(page-1)*pageSize),c.env.DB.prepare(`SELECT COUNT(*) total FROM worlds w WHERE ${clause}`).bind(...values)]);return c.json({items:(rows.results as unknown as WorldRow[]).map((row)=>present(row,userId)),pagination:{page,pageSize,total:Number((count.results[0] as {total:number}).total)}});});

worldRoutes.post('/',async(c)=>{const input=await readJson(c,worldInputSchema);const userId=c.get('user').id;await validateDefaultRpg(c.env,userId,input.defaultRpgId);const id=crypto.randomUUID(),now=nowIso(),slug=await uniqueSlug(c.env,userId,input.name);await c.env.DB.batch([c.env.DB.prepare(`INSERT INTO worlds (id,owner_user_id,name,slug,description,default_rpg_id,visibility,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'ACTIVE',?,?)`).bind(id,userId,input.name,slug,input.description,input.defaultRpgId??null,input.visibility,now,now),c.env.DB.prepare("INSERT INTO world_members (world_id,user_id,role,created_at) VALUES (?,?,'OWNER',?)").bind(id,userId,now)]);const row=await c.env.DB.prepare('SELECT w.*,r.title default_rpg_title,1 is_world_member FROM worlds w LEFT JOIN rpgs r ON r.id=w.default_rpg_id WHERE w.id=?').bind(id).first<WorldRow>();return c.json({item:present(row!,userId)},201);});

worldRoutes.get('/:id/entities',async(c)=>{await authorizedWorld(c,c.req.param('id'));const userId=c.get('user').id;const query=c.req.query();const page=Math.max(1,Number.parseInt(query.page??'1',10)||1),pageSize=Math.min(50,Math.max(1,Number.parseInt(query.pageSize??'18',10)||18));const authValues=entityAuthorizationValues(userId);const [rows,count]=await c.env.DB.batch([c.env.DB.prepare(`SELECT e.id,e.entity_type entityType,e.name,e.summary,e.visibility,e.archived_at archivedAt,${entityAuthorizationColumns()} FROM vault_entities e WHERE e.world_id=? AND e.archived_at IS NULL AND ${entityAuthorizationPredicate()} ORDER BY e.updated_at DESC LIMIT ? OFFSET ?`).bind(userId,userId,userId,userId,c.req.param('id'),...authValues,pageSize,(page-1)*pageSize),c.env.DB.prepare(`SELECT COUNT(*) total FROM vault_entities e WHERE e.world_id=? AND e.archived_at IS NULL AND ${entityAuthorizationPredicate()}`).bind(c.req.param('id'),...authValues)]);return c.json({items:rows.results,pagination:{page,pageSize,total:Number((count.results[0] as {total:number}).total)}});});

worldRoutes.get('/:id',async(c)=>{const base=await authorizedWorld(c,c.req.param('id'));const userId=c.get('user').id;const row=await c.env.DB.prepare('SELECT w.*,r.title default_rpg_title,? is_world_member FROM worlds w LEFT JOIN rpgs r ON r.id=w.default_rpg_id WHERE w.id=?').bind(base.is_world_member,c.req.param('id')).first<WorldRow>();const authValues=entityAuthorizationValues(userId);const [counts,recent,members]=await c.env.DB.batch([c.env.DB.prepare(`SELECT entity_type entityType,COUNT(*) count FROM vault_entities e WHERE e.world_id=? AND ${entityAuthorizationPredicate()} GROUP BY entity_type`).bind(c.req.param('id'),...authValues),c.env.DB.prepare(`SELECT e.id,e.entity_type entityType,e.name,e.summary,e.visibility,e.archived_at archivedAt FROM vault_entities e WHERE e.world_id=? AND ${entityAuthorizationPredicate()} ORDER BY e.updated_at DESC LIMIT 8`).bind(c.req.param('id'),...authValues),base.owner_user_id===userId?c.env.DB.prepare(`SELECT wm.user_id userId,u.display_name displayName,wm.role,wm.created_at createdAt FROM world_members wm JOIN users u ON u.id=wm.user_id WHERE wm.world_id=? ORDER BY CASE wm.role WHEN 'OWNER' THEN 0 ELSE 1 END,u.display_name`).bind(c.req.param('id')):c.env.DB.prepare('SELECT NULL WHERE 0')]);return c.json({item:present(row!,userId),counts:counts.results,recentEntities:recent.results,members:members.results});});

worldRoutes.patch('/:id',async(c)=>{const world=await ownedWorld(c,c.req.param('id'));if(world.archived_at)throw new ApiError(409,'WORLD_ARCHIVED','Restaure o mundo antes de editá-lo.');const input=await readJson(c,worldInputSchema);const userId=c.get('user').id;await validateDefaultRpg(c.env,userId,input.defaultRpgId);const slug=await uniqueSlug(c.env,userId,input.name,c.req.param('id'));await c.env.DB.prepare('UPDATE worlds SET name=?,slug=?,description=?,default_rpg_id=?,visibility=?,updated_at=? WHERE id=? AND owner_user_id=?').bind(input.name,slug,input.description,input.defaultRpgId??null,input.visibility,nowIso(),c.req.param('id'),userId).run();return c.json({success:true});});

worldRoutes.post('/:id/archive',async(c)=>{const world=await ownedWorld(c,c.req.param('id'));if(world.archived_at)throw new ApiError(409,'ALREADY_ARCHIVED','O mundo já está arquivado.');const now=nowIso();await c.env.DB.prepare("UPDATE worlds SET status='ARCHIVED',archived_at=?,updated_at=? WHERE id=? AND owner_user_id=?").bind(now,now,c.req.param('id'),c.get('user').id).run();return c.json({success:true});});
worldRoutes.post('/:id/restore',async(c)=>{const world=await ownedWorld(c,c.req.param('id'));if(!world.archived_at)throw new ApiError(409,'NOT_ARCHIVED','O mundo não está arquivado.');await c.env.DB.prepare("UPDATE worlds SET status='ACTIVE',archived_at=NULL,updated_at=? WHERE id=? AND owner_user_id=?").bind(nowIso(),c.req.param('id'),c.get('user').id).run();return c.json({success:true});});
worldRoutes.delete('/:id',async(c)=>{await ownedWorld(c,c.req.param('id'));const dependency=await c.env.DB.prepare('SELECT COUNT(*) total FROM vault_entities WHERE world_id=?').bind(c.req.param('id')).first<{total:number}>();if(Number(dependency?.total))throw new ApiError(409,'WORLD_HAS_ENTITIES','Arquive o mundo ou remova primeiro suas entidades.');await c.env.DB.prepare('DELETE FROM worlds WHERE id=? AND owner_user_id=?').bind(c.req.param('id'),c.get('user').id).run();return c.body(null,204);});

worldRoutes.post('/:id/members',async(c)=>{await ownedWorld(c,c.req.param('id'));const input=await readJson(c,worldMemberInputSchema);const user=await c.env.DB.prepare('SELECT id FROM users WHERE id=? AND disabled_at IS NULL AND deleted_at IS NULL').bind(input.userId).first();if(!user)throw new ApiError(422,'INVALID_WORLD_MEMBER','A conta selecionada não está disponível.');try{await c.env.DB.prepare("INSERT INTO world_members (world_id,user_id,role,created_at) VALUES (?,?,'VIEWER',?)").bind(c.req.param('id'),input.userId,nowIso()).run();}catch(error){if(String(error).includes('UNIQUE'))throw new ApiError(409,'DUPLICATE_WORLD_MEMBER','Esta conta já pertence ao mundo.');throw error;}return c.json({success:true},201);});
worldRoutes.delete('/:id/members/:userId',async(c)=>{const world=await ownedWorld(c,c.req.param('id'));if(c.req.param('userId')===world.owner_user_id)throw new ApiError(409,'OWNER_MEMBERSHIP','O owner não pode ser removido do mundo.');const result=await c.env.DB.prepare("DELETE FROM world_members WHERE world_id=? AND user_id=? AND role='VIEWER'").bind(c.req.param('id'),c.req.param('userId')).run();if(!result.meta.changes)throw new ApiError(404,'NOT_FOUND','Membro não encontrado.');return c.body(null,204);});
