const labels: Record<string, string> = {
  NONE: "Sem prioridade",
  LOW: "Baixa",
  MEDIUM: "Média",
  HIGH: "Alta",
  NOT_STARTED: "Não iniciado",
  READING: "Lendo",
  READ: "Lido",
  IDEA: "Ideia",
  PREPARING: "Preparando",
  SCHEDULED: "Agendada",
  PLAYING: "Jogando",
  COMPLETED: "Concluída",
  PLANNING: "Planejando",
  SESSION_ZERO: "Sessão Zero",
  IN_PROGRESS: "Em andamento",
  PAUSED: "Pausada",
  WEEKLY: "Semanal",
  BIWEEKLY: "Quinzenal",
  MONTHLY: "Mensal",
  BIMONTHLY: "Bimestral",
  IRREGULAR: "Irregular",
  PRIVATE: "Privado",
  GROUP: "Grupo",
  CAMPAIGN: "Campanha",
  PLAYERS: "Jogadores",
  GM_ONLY: "Somente narrador",
  ACTIVE: "Ativo",
  ARCHIVED: "Arquivado",
  OWNER: "Proprietário",
  VIEWER: "Membro",
  CHARACTER: "Personagem",
  NPC: "NPC",
  CREATURE: "Criatura",
  LOCATION: "Local",
  FACTION: "Facção",
  ITEM: "Item",
  LORE: "Lore",
  EVENT: "Evento",
  QUEST: "Missão",
  HANDOUT: "Material",
  ADVENTURE: "Adventure",
  ONE_SHOT: "One-Shot",
  SHORT_CAMPAIGN: "Campanha curta",
  LONG_CAMPAIGN: "Campanha longa",
  SANDBOX: "Sandbox",
  MODULE: "Módulo",
  CUSTOM: "Personalizada",
  REFERENCE: "Referência",
  HISTORY: "História",
  RELIGION: "Religião",
  CULTURE: "Cultura",
  LEGEND: "Lenda",
  PROPHECY: "Profecia",
  SECRET: "Segredo",
  DRAFT: "Rascunho",
  CANON: "Cânone",
  RUMOR: "Rumor",
  ENTITY: "Entidade",
  WORLD: "World",
  JOURNAL: "Diário",
  RPG: "RPG",
  ALLY: "Aliado",
  ENEMY: "Inimigo",
  RIVAL: "Rival",
  FAMILY: "Família",
  PARENT: "Pai ou mãe",
  CHILD: "Filho ou filha",
  SIBLING: "Irmãos",
  PARTNER: "Parceiros",
  ROMANCE: "Romance",
  EMPLOYER: "Empregador",
  SUBORDINATE: "Subordinado",
  MEMBER_OF: "Membro de",
  LEADER_OF: "Líder de",
  OWES: "Deve a",
  KNOWS: "Conhece",
};

export function displayLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return labels[value] ?? value.replaceAll("_", " ");
}
